from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

DEFAULT_CONFIG: dict[str, Any] = {
    "symbols": ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
    "stage1_symbols": [
        "SOLUSDT",
        "LABUSDT",
        "SUIUSDT",
        "AAVEUSDT",
        "WLDUSDT",
        "INUSDT",
        "RAVEUSDT",
        "TACUSDT",
        "TAIKOUSDT",
        "NFPUSDT",
        "ZBTUSDT",
        "JTOUSDT",
    ],
    "stage2_symbols": ["BTCUSDT", "ETHUSDT"],
    "auto_discover_symbols": True,
    "recall_pool_limit": 600,
    "coarse_pool_limit": 220,
    "rank_pool_limit": 90,
    "auction_pool_limit": 15,
    "scan_degrade_seconds": 18,
    "scan_min_rank_symbols": 8,
    "max_scan_symbols": 40,
    "min_24h_volume_usdt": 30_000_000,
    "max_observation_symbols": 45,
    "max_trade_pool_symbols": 20,
    "depth_check_top_symbols": 10,
    "depth_check_min_current_score": 38.0,
    "market_stream_enabled": True,
    "market_stream_dynamic_enabled": True,
    "market_stream_max_symbols": 50,
    "market_stream_auto_discover": True,
    "market_stream_rebuild_seconds": 60,
    "market_stream_rotation_threshold_pct": 20.0,
    "stream_hot_symbols_limit": 25,
    "stream_include_positions": True,
    "stream_include_live_credit": True,
    "symbol_trade_score": 75.0,
    "symbol_small_trade_score": 65.0,
    "symbol_observe_score": 50.0,
    "min_simulated_trades": 5,
    "min_simulated_win_rate": 45.0,
    "min_simulated_profit_factor": 1.25,
    "min_simulated_net_pct": 1.5,
    "live_performance_boost_enabled": True,
    "live_performance_window_hours": 36,
    "live_performance_min_closed_trades": 2,
    "live_performance_min_net_pnl_usdt": 0.5,
    "live_performance_min_profit_factor": 1.05,
    "live_performance_min_depth_notional_usdt": 1_500,
    "live_performance_min_sim_net_pct": 5.0,
    "live_performance_risk_multiplier": 0.6,
    "live_performance_check_min_score": 70.0,
    "live_credit_enabled": True,
    "live_credit_default_score": 50.0,
    "live_credit_history_hours": 96,
    "live_credit_sync_seconds": 600,
    "live_credit_score_weight": 0.35,
    "live_credit_multiplier_divisor": 50.0,
    "live_credit_max_risk_multiplier": 2.0,
    "live_credit_fuse_score": 2.0,
    "live_credit_recovery_enabled": True,
    "live_credit_recovery_interval_hours": 6,
    "live_credit_recovery_points": 3.0,
    "live_credit_low_recovery_interval_hours": 12,
    "live_credit_low_recovery_points": 2.0,
    "live_credit_recovery_cap": 50.0,
    "live_credit_loss_cooldown_cap": 0.60,
    "live_credit_quick_loss_cooldown_cap": 0.40,
    "live_credit_two_loss_cooldown_cap": 0.25,
    "live_credit_three_loss_cooldown_cap": 0.10,
    "live_credit_quick_stop_seconds": 60,
    "live_credit_loss_cooldown_minutes": 15,
    "live_credit_quick_stop_cooldown_hours": 0.5,
    "live_credit_two_loss_cooldown_hours": 1,
    "live_credit_three_loss_cooldown_hours": 3,
    "live_credit_penalty_cooldown_hours": 12,
    "live_credit_cooldown_bypass_enabled": True,
    "live_credit_cooldown_bypass_min_score": 95.0,
    "live_credit_cooldown_bypass_min_cost_ratio": 18.0,
    "live_credit_big_win_usdt": 0.7,
    "live_credit_large_win_usdt": 2.0,
    "live_credit_big_loss_usdt": 0.7,
    "live_credit_large_loss_usdt": 2.0,
    "live_credit_min_quality_hold_seconds": 90,
    "live_credit_tail_win_count": 3,
    "live_credit_tail_risk_multiplier": 0.75,
    "live_credit_tail_score_penalty": 3.0,
    "live_credit_sync_max_symbols": 20,
    "new_symbol_observation_minutes": 30,
    "small_trade_risk_multiplier": 0.5,
    "max_spread_pct": 0.08,
    "min_depth_notional_usdt": 20_000,
    "volume_spike_ratio": 1.8,
    "quality_backtest_days": [3, 5],
    "interval": "4h",
    "conservative_interval": "4h",
    "balanced_interval": "1h",
    "attack_interval": "15m",
    "tournament_interval": "5m",
    "tournament_sprint_interval": "5m",
    "conservative_recent_days": 30,
    "balanced_recent_days": 20,
    "attack_recent_days": 10,
    "tournament_recent_days": 5,
    "tournament_sprint_recent_days": 3,
    "conservative_loop_seconds": 300,
    "balanced_loop_seconds": 120,
    "attack_loop_seconds": 60,
    "tournament_loop_seconds": 30,
    "tournament_sprint_loop_seconds": 20,
    "limit": 1000,
    "stage1_target_equity": 10000.0,
    "stage2_activation": "manual",
    "growth_mode": "balanced",
    "tournament_stop_equity": 30.0,
    "auto_risk_by_equity": True,
    "risk_per_trade_pct": 1.0,
    "attack_risk_per_trade_pct": 5.0,
    "tournament_risk_per_trade_pct": 15.0,
    "tournament_sprint_risk_per_trade_pct": 18.0,
    "daily_loss_limit_pct": 3.0,
    "attack_daily_loss_limit_pct": 10.0,
    "tournament_daily_loss_limit_pct": 25.0,
    "tournament_sprint_daily_loss_limit_pct": 35.0,
    "max_drawdown_pct": 15.0,
    "max_consecutive_losses": 2,
    "cooldown_hours": 24,
    "max_open_positions": 1,
    "tournament_sprint_max_open_positions": 1,
    "tournament_sprint_second_position_equity": 100.0,
    "position_rotation_enabled": True,
    "tournament_rotation_enabled": True,
    "tournament_sprint_rotation_enabled": True,
    "attack_rotation_enabled": True,
    "balanced_rotation_enabled": True,
    "conservative_rotation_enabled": False,
    "tournament_rotation_min_new_score": 95.0,
    "tournament_sprint_rotation_min_new_score": 88.0,
    "attack_rotation_min_new_score": 100.0,
    "balanced_rotation_min_new_score": 110.0,
    "conservative_rotation_min_new_score": 130.0,
    "tournament_rotation_min_score_delta": 12.0,
    "tournament_sprint_rotation_min_score_delta": 8.0,
    "attack_rotation_min_score_delta": 18.0,
    "balanced_rotation_min_score_delta": 25.0,
    "conservative_rotation_min_score_delta": 999.0,
    "rotation_min_cost_ratio": 8.0,
    "rotation_unknown_position_score": 75.0,
    "rotation_keep_winner_profit_pct": 3.0,
    "rotation_max_current_loss_pct": 6.0,
    "rotation_cooldown_minutes": 45,
    "max_symbol_margin_pct": 35.0,
    "attack_max_symbol_margin_pct": 60.0,
    "tournament_max_symbol_margin_pct": 90.0,
    "tournament_sprint_max_symbol_margin_pct": 95.0,
    "stage1_max_leverage": 2,
    "attack_max_leverage": 3,
    "tournament_max_leverage": 5,
    "tournament_sprint_max_leverage": 5,
    "stage2_max_leverage": 1.5,
    "min_recent_trades": 2,
    "min_profit_factor": 1.2,
    "min_expected_profit_cost_ratio": 3.0,
    "estimated_slippage_pct": 0.04,
    "min_expected_profit_pct": 0.35,
    "preemptive_entries_enabled": True,
    "preemptive_min_score": 72.0,
    "standard_min_score": 85.0,
    "preemptive_risk_multiplier": 0.24,
    "short_preemptive_risk_multiplier": 0.18,
    "preemptive_max_distance_pct": 0.35,
    "tournament_sprint_enabled": True,
    "tournament_sprint_auto_under_equity": 100.0,
    "tournament_sprint_standard_min_score": 72.0,
    "tournament_sprint_preemptive_min_score": 58.0,
    "tournament_sprint_preemptive_max_distance_pct": 0.55,
    "tournament_sprint_preemptive_risk_multiplier": 0.35,
    "tournament_sprint_short_preemptive_risk_multiplier": 0.25,
    "tournament_sprint_momentum_enabled": True,
    "tournament_sprint_momentum_min_score": 54.0,
    "tournament_sprint_momentum_min_candle_pct": 0.10,
    "tournament_sprint_min_expected_profit_cost_ratio": 1.35,
    "tournament_sprint_min_expected_profit_pct": 0.22,
    "tournament_sprint_standard_stop_atr": 0.9,
    "tournament_sprint_standard_take_profit_atr": 1.4,
    "tournament_sprint_standard_max_hold_bars": 6,
    "tournament_sprint_preemptive_stop_atr": 0.75,
    "tournament_sprint_preemptive_take_profit_atr": 1.0,
    "tournament_sprint_preemptive_max_hold_bars": 4,
    "tournament_sprint_momentum_stop_atr": 0.8,
    "tournament_sprint_momentum_take_profit_atr": 1.2,
    "tournament_sprint_momentum_max_hold_bars": 5,
    "tournament_sprint_short_min_recent_trades": 3,
    "tournament_sprint_short_min_profit_factor": 1.05,
    "tournament_sprint_short_min_net_pct": -2.0,
    "tournament_sprint_long_min_profit_factor": 0.85,
    "tournament_sprint_long_min_net_pct": -3.0,
    "tournament_sprint_max_consecutive_losses": 4,
    "quality_mode_weights_enabled": True,
    "sprint_symbol_trade_score": 68.0,
    "sprint_symbol_small_trade_score": 55.0,
    "sprint_symbol_hot_observe_score": 45.0,
    "sprint_atr_ideal_min_pct": 1.2,
    "sprint_atr_ideal_max_pct": 7.0,
    "sprint_atr_high_pct": 10.0,
    "sprint_high_atr_risk_multiplier": 0.6,
    "sprint_sample_penalty": 1.0,
    "sprint_sample_penalty_exempt_spike": 2.5,
    "sprint_sample_low_risk_multiplier": 0.75,
    "sprint_hot_observe_risk_multiplier": 0.35,
    "sprint_extreme_depth_notional_usdt": 50_000.0,
    "observe_breakout_enabled": True,
    "observe_breakout_min_score": 105.0,
    "observe_breakout_min_quality": 78.0,
    "observe_breakout_min_cost_ratio": 20.0,
    "observe_breakout_min_profit_factor": 1.5,
    "observe_breakout_min_net_pct": 4.0,
    "observe_breakout_min_depth_notional_usdt": 500.0,
    "observe_breakout_max_spread_pct": 0.08,
    "observe_breakout_risk_multiplier": 0.22,
    "observe_low_price_threshold": 0.01,
    "observe_low_price_risk_multiplier": 0.75,
    "observe_high_atr_pct": 3.0,
    "observe_high_atr_risk_multiplier": 0.75,
    "observe_extreme_atr_pct": 3.0,
    "observe_extreme_depth_notional_usdt": 5_000.0,
    "observe_consecutive_loss_count": 2,
    "observe_consecutive_loss_risk_multiplier": 0.5,
    "directional_cooldown_enabled": True,
    "legacy_symbol_cooldown_blocks": False,
    "symbol_cooldown_minutes": 0,
    "stop_loss_cooldown_minutes": 30,
    "allow_short": True,
    "short_risk_multiplier": 0.5,
    "short_min_recent_trades": 5,
    "short_min_profit_factor": 1.3,
    "short_min_net_pct": 1.0,
    "grid_enabled": True,
    "grid_min_levels": 20,
    "grid_max_levels": 80,
    "grid_reserve_cash_pct": 25.0,
    "grid_stop_on_breakout": True,
    "dry_run": True,
    "live_trading_enabled": False,
    "live_trading_confirmation": "",
    "binance_base_url": "https://fapi.binance.com",
    "api_key": "",
    "api_secret": "",
}


def config_path() -> Path:
    return Path(os.getenv("APP_CONFIG_PATH", "./data/config.json"))


def load_config(include_secret: bool = True) -> dict[str, Any]:
    path = config_path()
    config = DEFAULT_CONFIG.copy()
    if path.exists():
        with path.open("r", encoding="utf-8") as file:
            config.update(json.load(file))
    if not include_secret:
        config["api_secret"] = "********" if config.get("api_secret") else ""
        config["api_key"] = mask(config.get("api_key", ""))
    return config


def save_config(payload: dict[str, Any]) -> dict[str, Any]:
    current = load_config(include_secret=True)
    if "api_key" in payload and isinstance(payload.get("api_key"), str):
        payload["api_key"] = payload["api_key"].strip()
    if "api_secret" in payload and isinstance(payload.get("api_secret"), str):
        payload["api_secret"] = payload["api_secret"].strip()
    if "binance_base_url" in payload and isinstance(payload.get("binance_base_url"), str):
        payload["binance_base_url"] = payload["binance_base_url"].strip()
    if payload.get("api_secret") in {"", "********"} and current.get("api_secret"):
        payload = {key: value for key, value in payload.items() if key != "api_secret"}
    if (
        ("..." in str(payload.get("api_key", "")) or payload.get("api_key") in {"", "****"})
        and current.get("api_key")
    ):
        payload = {key: value for key, value in payload.items() if key != "api_key"}
    current.update(payload)
    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(current, file, ensure_ascii=False, indent=2)
    return load_config(include_secret=False)


def mask(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "****"
    return f"{value[:4]}...{value[-4:]}"
