from __future__ import annotations

from pydantic import BaseModel, Field


class TradingConfig(BaseModel):
    symbols: list[str] = Field(default_factory=lambda: ["BTCUSDT", "ETHUSDT", "SOLUSDT"])
    stage1_symbols: list[str] = Field(default_factory=lambda: ["SOLUSDT", "LABUSDT", "SUIUSDT", "AAVEUSDT", "WLDUSDT"])
    stage2_symbols: list[str] = Field(default_factory=lambda: ["BTCUSDT", "ETHUSDT"])
    auto_discover_symbols: bool = True
    recall_pool_limit: int = Field(default=600, ge=1, le=1000)
    coarse_pool_limit: int = Field(default=220, ge=1, le=500)
    rank_pool_limit: int = Field(default=90, ge=1, le=200)
    auction_pool_limit: int = Field(default=15, ge=0, le=50)
    scan_degrade_seconds: int = Field(default=18, ge=5, le=300)
    scan_min_rank_symbols: int = Field(default=8, ge=1, le=200)
    max_scan_symbols: int = Field(default=120, ge=1, le=200)
    min_24h_volume_usdt: float = Field(default=30_000_000, ge=0)
    max_observation_symbols: int = Field(default=45, ge=1, le=150)
    max_trade_pool_symbols: int = Field(default=20, ge=1, le=50)
    depth_check_top_symbols: int = Field(default=10, ge=0, le=50)
    depth_check_min_current_score: float = Field(default=38.0, ge=0, le=200)
    market_stream_enabled: bool = True
    market_stream_dynamic_enabled: bool = True
    market_stream_max_symbols: int = Field(default=150, ge=1, le=250)
    market_stream_min_24h_volume_usdt: float = Field(default=5_000_000, ge=0)
    market_stream_symbols_per_connection: int = Field(default=75, ge=10, le=200)
    market_stream_auto_discover: bool = True
    market_stream_rebuild_seconds: int = Field(default=300, ge=15, le=1800)
    market_stream_rotation_threshold_pct: float = Field(default=20.0, ge=0, le=100)
    market_stream_persist_seconds: float = Field(default=5.0, ge=1, le=60)
    orderbook_full_stream_enabled: bool = True
    orderbook_full_symbols_limit: int = Field(default=20, ge=0, le=50)
    orderbook_snapshot_limit: int = Field(default=100, ge=20, le=1000)
    orderbook_snapshot_concurrency: int = Field(default=4, ge=1, le=8)
    yolo_scalp_trade_flow_enabled: bool = True
    yolo_scalp_trade_flow_window_seconds: float = Field(default=5.0, ge=1, le=60)
    yolo_scalp_trade_flow_min_notional_usdt: float = Field(default=1000.0, ge=0)
    yolo_scalp_trade_flow_weight: float = Field(default=0.35, ge=0, le=0.8)
    yolo_scalp_trade_flow_trigger_notional_usdt: float = Field(default=100_000.0, ge=0)
    yolo_scalp_trade_flow_trigger_imbalance: float = Field(default=0.15, ge=0, le=1)
    microstructure_research_enabled: bool = True
    microstructure_research_symbol_limit: int = Field(default=12, ge=1, le=50)
    microstructure_research_candidate_limit: int = Field(default=8, ge=1, le=30)
    microstructure_research_stream_max_age_seconds: int = Field(default=8, ge=1, le=60)
    microstructure_research_min_depth_notional_usdt: float = Field(default=750.0, ge=0)
    microstructure_research_max_spread_pct: float = Field(default=0.10, ge=0, le=5)
    microstructure_research_min_flow_notional_usdt: float = Field(default=15_000.0, ge=0)
    microstructure_research_min_abs_imbalance: float = Field(default=0.10, ge=0, le=1)
    microstructure_research_min_confirmations: int = Field(default=4, ge=1, le=5)
    microstructure_research_stop_pct: float = Field(default=0.25, ge=0.05, le=5)
    microstructure_research_take_profit_pct: float = Field(default=0.35, ge=0.05, le=10)
    microstructure_research_max_hold_minutes: int = Field(default=5, ge=1, le=60)
    user_stream_enabled: bool = True
    user_stream_keepalive_seconds: int = Field(default=1800, ge=300, le=3600)
    user_stream_reconnect_seconds: int = Field(default=5, ge=1, le=300)
    user_stream_max_session_seconds: int = Field(default=82_800, ge=3600, le=86_400)
    user_stream_account_max_age_seconds: int = Field(default=90, ge=5, le=3600)
    account_projection_ws_max_age_seconds: int = Field(default=45, ge=5, le=300)
    account_projection_available_balance_max_age_seconds: int = Field(default=15, ge=1, le=120)
    account_projection_refresh_before_sizing: bool = True
    account_projection_balance_mismatch_pct: float = Field(default=2.0, ge=0.1, le=25.0)
    account_supervisor_enabled: bool = True
    account_supervisor_poll_seconds: int = Field(default=2, ge=1, le=60)
    account_supervisor_position_audit_seconds: int = Field(default=10, ge=2, le=300)
    account_supervisor_idle_audit_seconds: int = Field(default=30, ge=5, le=600)
    fast_lane_enabled: bool = True
    fast_lane_poll_seconds: int = Field(default=2, ge=1, le=60)
    background_scan_min_interval_seconds: int = Field(default=30, ge=10, le=3600)
    background_scan_timeout_seconds: int = Field(default=90, ge=30, le=1800)
    background_scan_watchdog_seconds: int = Field(default=5, ge=1, le=60)
    background_scan_restart_enabled: bool = True
    fast_lane_symbol_cooldown_seconds: int = Field(default=10, ge=1, le=300)
    fast_lane_event_max_age_seconds: int = Field(default=45, ge=5, le=600)
    fast_lane_max_symbols: int = Field(default=3, ge=1, le=20)
    fast_lane_depth_checks: int = Field(default=3, ge=0, le=20)
    fast_lane_budget_seconds: float = Field(default=5.0, ge=1, le=60)
    smart_flow_enabled: bool = True
    smart_flow_live_soft_score_enabled: bool = True
    smart_flow_symbol_limit: int = Field(default=12, ge=0, le=50)
    smart_flow_cache_seconds: int = Field(default=300, ge=60, le=3600)
    smart_flow_period: str = "5m"
    smart_flow_history_points: int = Field(default=12, ge=2, le=500)
    smart_flow_max_soft_points: float = Field(default=5.0, ge=0, le=10)
    smart_flow_min_confidence: float = Field(default=0.45, ge=0, le=1)
    telemetry_retention_days: int = Field(default=14, ge=7, le=3650)
    strategy_run_retention_days: int = Field(default=2, ge=1, le=365)
    shadow_trade_retention_days: int = Field(default=14, ge=1, le=365)
    telemetry_maintenance_batch_size: int = Field(default=50_000, ge=100, le=500_000)
    telemetry_maintenance_max_batches: int = Field(default=4, ge=1, le=20)
    performance_guard_enabled: bool = True
    performance_guard_cache_seconds: int = Field(default=15, ge=1, le=300)
    performance_guard_live_window_trades: int = Field(default=10, ge=3, le=200)
    performance_guard_shadow_window_trades: int = Field(default=100, ge=10, le=2000)
    performance_guard_min_live_trades: int = Field(default=10, ge=3, le=200)
    performance_guard_min_shadow_trades: int = Field(default=50, ge=10, le=2000)
    performance_guard_max_bad_profit_factor: float = Field(default=0.8, ge=0, le=10)
    performance_guard_max_bad_win_rate: float = Field(default=25.0, ge=0, le=100)
    performance_guard_severe_profit_factor: float = Field(default=0.5, ge=0, le=10)
    performance_guard_severe_win_rate: float = Field(default=20.0, ge=0, le=100)
    performance_guard_severe_consecutive_losses: int = Field(default=4, ge=1, le=50)
    performance_guard_severe_window_loss_equity_pct: float = Field(default=8.0, ge=0, le=100)
    performance_guard_peak_lookback_hours: int = Field(default=24, ge=1, le=720)
    performance_guard_peak_drawdown_pct: float = Field(default=12.0, ge=0, le=100)
    performance_guard_pause_minutes: int = Field(default=120, ge=1, le=1440)
    performance_guard_soft_consecutive_losses: int = Field(default=4, ge=1, le=50)
    performance_guard_soft_window_loss_equity_pct: float = Field(default=8.0, ge=0, le=100)
    performance_guard_soft_peak_drawdown_pct: float = Field(default=12.0, ge=0, le=100)
    performance_guard_soft_observation_minutes: int = Field(default=20, ge=0, le=1440)
    performance_guard_hard_consecutive_losses: int = Field(default=5, ge=1, le=50)
    performance_guard_hard_window_loss_equity_pct: float = Field(default=12.0, ge=0, le=100)
    performance_guard_hard_peak_drawdown_pct: float = Field(default=15.0, ge=0, le=100)
    performance_guard_hard_pause_minutes: int = Field(default=60, ge=1, le=1440)
    performance_guard_recovery_risk_multiplier: float = Field(default=0.20, ge=0.01, le=1)
    performance_guard_recovery_level_1_multiplier: float = Field(default=0.20, ge=0.01, le=1)
    performance_guard_recovery_level_2_multiplier: float = Field(default=0.40, ge=0.01, le=1)
    performance_guard_recovery_level_3_multiplier: float = Field(default=0.70, ge=0.01, le=1)
    performance_guard_current_release_only: bool = True
    performance_guard_recovery_shadow_trades: int = Field(default=20, ge=10, le=500)
    performance_recovery_permit_enabled: bool = True
    performance_recovery_entry_profit_factor: float = Field(default=0.90, ge=0, le=10)
    performance_recovery_confirm_closes: int = Field(default=3, ge=1, le=50)
    performance_recovery_confirm_minutes: int = Field(default=5, ge=0, le=1440)
    performance_recovery_permit_minutes: int = Field(default=180, ge=5, le=1440)
    performance_recovery_revoke_profit_factor: float = Field(default=0.50, ge=0, le=10)
    performance_recovery_revoke_new_shadow_trades: int = Field(default=3, ge=1, le=100)
    performance_recovery_current_live_warmup_trades: int = Field(default=8, ge=1, le=100)
    performance_recovery_normal_live_profit_factor: float = Field(default=1.05, ge=0, le=10)
    equity_guard_release_baseline_enabled: bool = True
    strategy_evidence_enabled: bool = True
    strategy_evidence_window_hours: int = Field(default=24, ge=1, le=720)
    strategy_evidence_live_confirm_trades: int = Field(default=8, ge=1, le=200)
    strategy_evidence_shadow_confirm_trades: int = Field(default=30, ge=1, le=2000)
    strategy_evidence_live_confirm_pf: float = Field(default=1.1, ge=0, le=20)
    strategy_evidence_shadow_confirm_pf: float = Field(default=1.2, ge=0, le=20)
    strategy_evidence_live_negative_trades: int = Field(default=2, ge=1, le=200)
    strategy_evidence_shadow_negative_trades: int = Field(default=10, ge=1, le=2000)
    strategy_evidence_signal_negative_trades: int = Field(default=10, ge=1, le=2000)
    strategy_evidence_negative_pf: float = Field(default=0.8, ge=0, le=20)
    strategy_evidence_recovery_block_negative: bool = True
    strategy_evidence_positive_risk_cap: float = Field(default=1.15, ge=0, le=2)
    strategy_evidence_weak_risk_cap: float = Field(default=0.50, ge=0, le=1)
    strategy_evidence_negative_risk_cap: float = Field(default=0.25, ge=0, le=1)
    strategy_evidence_direction_negative_risk_cap: float = Field(default=0.50, ge=0, le=1)
    strategy_evidence_loss_reentry_minutes: int = Field(default=30, ge=0, le=1440)
    observed_cost_window_trades: int = Field(default=50, ge=1, le=1000)
    observed_cost_safety_multiplier: float = Field(default=1.15, ge=1, le=5)
    stream_hot_symbols_limit: int = Field(default=40, ge=0, le=200)
    stream_include_positions: bool = True
    stream_include_live_credit: bool = True
    opportunity_queue_enabled: bool = True
    opportunity_queue_ttl_seconds: int = Field(default=240, ge=10, le=3600)
    opportunity_queue_max_events: int = Field(default=240, ge=1, le=1000)
    opportunity_queue_scan_limit: int = Field(default=80, ge=1, le=500)
    opportunity_queue_score_weight: float = Field(default=0.35, ge=0, le=2)
    opportunity_queue_min_score: float = Field(default=20.0, ge=0, le=200)
    symbol_trade_score: float = Field(default=75.0, ge=0, le=100)
    symbol_small_trade_score: float = Field(default=65.0, ge=0, le=100)
    symbol_observe_score: float = Field(default=50.0, ge=0, le=100)
    min_simulated_trades: int = Field(default=5, ge=0, le=100)
    min_simulated_win_rate: float = Field(default=45.0, ge=0, le=100)
    min_simulated_profit_factor: float = Field(default=1.25, ge=0, le=20)
    min_simulated_net_pct: float = Field(default=1.5, ge=-100, le=500)
    live_performance_boost_enabled: bool = True
    live_performance_window_hours: int = Field(default=36, ge=1, le=168)
    live_performance_min_closed_trades: int = Field(default=2, ge=1, le=50)
    live_performance_min_net_pnl_usdt: float = Field(default=0.5, ge=-100, le=1000)
    live_performance_min_profit_factor: float = Field(default=1.05, ge=0, le=20)
    live_performance_min_depth_notional_usdt: float = Field(default=1_500, ge=0)
    live_performance_min_sim_net_pct: float = Field(default=5.0, ge=-100, le=500)
    live_performance_risk_multiplier: float = Field(default=0.6, ge=0.05, le=1)
    live_performance_check_min_score: float = Field(default=70.0, ge=0, le=200)
    live_credit_enabled: bool = True
    strategy_family_credit_enabled: bool = True
    live_credit_default_score: float = Field(default=50.0, ge=0, le=100)
    live_credit_history_hours: int = Field(default=96, ge=1, le=720)
    live_credit_sync_seconds: int = Field(default=600, ge=60, le=86400)
    live_credit_score_weight: float = Field(default=0.35, ge=0, le=2)
    live_credit_multiplier_divisor: float = Field(default=50.0, ge=1, le=100)
    live_credit_max_risk_multiplier: float = Field(default=2.0, ge=0.1, le=3)
    live_credit_fuse_score: float = Field(default=2.0, ge=0, le=20)
    live_credit_recovery_enabled: bool = True
    live_credit_recovery_interval_hours: int = Field(default=6, ge=1, le=168)
    live_credit_recovery_points: float = Field(default=3.0, ge=0, le=50)
    live_credit_low_recovery_interval_hours: int = Field(default=12, ge=1, le=168)
    live_credit_low_recovery_points: float = Field(default=2.0, ge=0, le=50)
    live_credit_recovery_cap: float = Field(default=50.0, ge=0, le=100)
    live_credit_loss_cooldown_cap: float = Field(default=0.60, ge=0, le=2)
    live_credit_quick_loss_cooldown_cap: float = Field(default=0.40, ge=0, le=2)
    live_credit_two_loss_cooldown_cap: float = Field(default=0.25, ge=0, le=2)
    live_credit_three_loss_cooldown_cap: float = Field(default=0.10, ge=0, le=2)
    live_credit_quick_stop_seconds: int = Field(default=60, ge=1, le=3600)
    live_credit_loss_cooldown_minutes: int = Field(default=15, ge=0, le=1440)
    live_credit_quick_stop_cooldown_hours: float = Field(default=0.5, ge=0, le=72)
    live_credit_two_loss_cooldown_hours: float = Field(default=1, ge=0, le=168)
    live_credit_three_loss_cooldown_hours: float = Field(default=3, ge=0, le=720)
    live_credit_penalty_cooldown_hours: int = Field(default=12, ge=0, le=720)
    live_credit_cooldown_bypass_enabled: bool = True
    live_credit_cooldown_bypass_min_score: float = Field(default=95.0, ge=0, le=200)
    live_credit_cooldown_bypass_min_cost_ratio: float = Field(default=18.0, ge=0, le=200)
    live_credit_big_win_usdt: float = Field(default=0.7, ge=0, le=1000)
    live_credit_large_win_usdt: float = Field(default=2.0, ge=0, le=1000)
    live_credit_big_loss_usdt: float = Field(default=0.7, ge=0, le=1000)
    live_credit_large_loss_usdt: float = Field(default=2.0, ge=0, le=1000)
    live_credit_win_reward: float = Field(default=4.0, ge=0, le=50)
    live_credit_net_profit_reward_per_usdt: float = Field(default=1.5, ge=0, le=50)
    live_credit_low_fee_reward: float = Field(default=1.5, ge=0, le=20)
    live_credit_loss_penalty: float = Field(default=6.0, ge=0, le=50)
    live_credit_consecutive_loss_penalty: float = Field(default=10.0, ge=0, le=100)
    live_credit_fee_drag_penalty: float = Field(default=3.0, ge=0, le=50)
    live_credit_min_quality_hold_seconds: int = Field(default=90, ge=0, le=86400)
    live_credit_tail_win_count: int = Field(default=3, ge=1, le=20)
    live_credit_tail_risk_multiplier: float = Field(default=0.75, ge=0.05, le=1)
    live_credit_tail_score_penalty: float = Field(default=3.0, ge=0, le=50)
    live_credit_sync_max_symbols: int = Field(default=20, ge=1, le=100)
    live_credit_time_decay_enabled: bool = True
    live_credit_decay_half_life_hours: float = Field(default=12.0, ge=1, le=720)
    live_credit_decay_floor: float = Field(default=0.15, ge=0, le=1)
    live_credit_recent_3h_multiplier: float = Field(default=1.5, ge=0, le=5)
    live_credit_recent_24h_multiplier: float = Field(default=1.0, ge=0, le=5)
    live_credit_old_multiplier: float = Field(default=0.6, ge=0, le=5)
    live_credit_fee_pressure_enabled: bool = True
    live_credit_fee_pressure_ratio: float = Field(default=0.20, ge=0, le=100)
    live_credit_fee_pressure_risk_multiplier: float = Field(default=0.75, ge=0, le=2)
    live_credit_boost_requires_profitability: bool = True
    live_credit_boost_min_closed_trades: int = Field(default=3, ge=0, le=100)
    live_credit_boost_min_net_pnl_usdt: float = Field(default=0.2, ge=-1000, le=1000)
    live_credit_boost_min_profit_factor: float = Field(default=1.2, ge=0, le=1000)
    live_credit_boost_max_fee_to_net_ratio: float = Field(default=0.35, ge=0, le=1000)
    live_credit_unqualified_boost_cap: float = Field(default=1.0, ge=0, le=3)
    live_credit_streak_profit_multiplier: float = Field(default=1.15, ge=0.1, le=3)
    live_reaction_enabled: bool = True
    live_reaction_check_seconds: int = Field(default=20, ge=5, le=3600)
    live_reaction_background_check_seconds: int = Field(default=180, ge=20, le=3600)
    live_reaction_sync_lookback_minutes: int = Field(default=180, ge=10, le=1440)
    live_reaction_sync_max_symbols: int = Field(default=8, ge=1, le=50)
    live_reaction_history_hours: int = Field(default=96, ge=1, le=720)
    live_reaction_one_loss_cooldown_minutes: int = Field(default=5, ge=0, le=1440)
    live_reaction_one_loss_multiplier: float = Field(default=0.4, ge=0, le=1)
    live_reaction_two_loss_ban_minutes: int = Field(default=30, ge=0, le=1440)
    live_reaction_three_loss_ban_hours: float = Field(default=4, ge=0, le=720)
    live_reaction_recent_loss_window_minutes: int = Field(default=10, ge=1, le=1440)
    live_reaction_recent_loss_equity_pct: float = Field(default=12.0, ge=0, le=100)
    live_reaction_recent_loss_ban_minutes: int = Field(default=120, ge=0, le=2880)
    live_reaction_symbol_direction_daily_loss_pct: float = Field(default=15.0, ge=0, le=100)
    live_reaction_single_loss_cooldown_equity_pct: float = Field(default=6.0, ge=0, le=100)
    live_reaction_single_loss_ban_equity_pct: float = Field(default=10.0, ge=0, le=100)
    live_reaction_single_loss_cooldown_minutes: int = Field(default=60, ge=0, le=2880)
    live_reaction_single_loss_ban_minutes: int = Field(default=180, ge=0, le=2880)
    live_reaction_giveback_min_profit_usdt: float = Field(default=1.0, ge=0, le=1000000)
    live_reaction_giveback_cooldown_pct: float = Field(default=50.0, ge=0, le=100)
    live_reaction_giveback_ban_pct: float = Field(default=80.0, ge=0, le=100)
    live_reaction_giveback_cooldown_minutes: int = Field(default=60, ge=0, le=2880)
    live_reaction_giveback_ban_minutes: int = Field(default=180, ge=0, le=2880)
    live_reaction_profit_tail_count: int = Field(default=2, ge=1, le=20)
    live_reaction_tail_multiplier: float = Field(default=0.5, ge=0, le=1)
    live_reaction_tail_cooldown_minutes: int = Field(default=15, ge=0, le=1440)
    live_reaction_tail_loss_cooldown_minutes: int = Field(default=30, ge=0, le=1440)
    live_reaction_score_penalty: float = Field(default=8.0, ge=0, le=100)
    live_reaction_tail_score_penalty: float = Field(default=5.0, ge=0, le=100)
    new_symbol_observation_minutes: int = Field(default=30, ge=0, le=1440)
    small_trade_risk_multiplier: float = Field(default=0.5, ge=0.05, le=1)
    max_spread_pct: float = Field(default=0.08, ge=0, le=5)
    min_depth_notional_usdt: float = Field(default=20_000, ge=0)
    volume_spike_ratio: float = Field(default=1.8, ge=0, le=20)
    adaptive_thresholds_enabled: bool = True
    adaptive_volume_spike_floor: float = Field(default=1.2, ge=0, le=20)
    adaptive_volume_spike_ceiling: float = Field(default=2.4, ge=0, le=20)
    adaptive_firecracker_move_floor_pct: float = Field(default=4.0, ge=0, le=200)
    adaptive_firecracker_move_ceiling_pct: float = Field(default=14.0, ge=0, le=200)
    quality_backtest_days: list[int] = Field(default_factory=lambda: [3, 5])
    interval: str = "4h"
    conservative_interval: str = "4h"
    balanced_interval: str = "1h"
    attack_interval: str = "15m"
    tournament_interval: str = "5m"
    tournament_sprint_interval: str = "5m"
    conservative_recent_days: int = Field(default=30, ge=1, le=120)
    balanced_recent_days: int = Field(default=20, ge=1, le=120)
    attack_recent_days: int = Field(default=10, ge=1, le=60)
    tournament_recent_days: int = Field(default=5, ge=1, le=30)
    tournament_sprint_recent_days: int = Field(default=3, ge=1, le=14)
    conservative_loop_seconds: int = Field(default=300, ge=10, le=3600)
    balanced_loop_seconds: int = Field(default=120, ge=10, le=3600)
    attack_loop_seconds: int = Field(default=60, ge=10, le=3600)
    tournament_loop_seconds: int = Field(default=30, ge=10, le=3600)
    tournament_sprint_loop_seconds: int = Field(default=20, ge=10, le=3600)
    extreme_sprint_loop_seconds: int = Field(default=15, ge=5, le=3600)
    yolo_scalp_loop_seconds: int = Field(default=8, ge=3, le=3600)
    limit: int = Field(default=1000, ge=100, le=1500)
    stage1_target_equity: float = Field(default=10000.0, gt=0)
    stage2_activation: str = "manual"
    target_controller_enabled: bool = True
    target_risk_adjustment_enabled: bool = False
    target_phase_a_equity: float = Field(default=10000.0, ge=1)
    target_phase_b_equity: float = Field(default=100000.0, ge=1)
    target_phase_c_equity: float = Field(default=1000000.0, ge=1)
    target_phase_days: int = Field(default=30, ge=1, le=365)
    target_progress_ahead_multiplier: float = Field(default=0.75, ge=0.01, le=5)
    target_progress_on_track_multiplier: float = Field(default=1.0, ge=0.01, le=5)
    target_progress_behind_multiplier: float = Field(default=1.2, ge=0.01, le=5)
    target_progress_critical_multiplier: float = Field(default=1.5, ge=0.01, le=5)
    target_progress_max_multiplier: float = Field(default=1.8, ge=0.01, le=10)
    target_progress_min_multiplier: float = Field(default=0.5, ge=0.01, le=5)
    target_hard_floor_pct: float = Field(default=35.0, ge=0, le=100)
    target_critical_gap_pct: float = Field(default=35.0, ge=0, le=100)
    target_ahead_gap_pct: float = Field(default=15.0, ge=0, le=100)
    daily_learning_report_enabled: bool = True
    simulation_trades_per_day: float = Field(default=3.0, ge=0, le=200)
    simulation_fee_slippage_pct: float = Field(default=0.12, ge=0, le=10)
    simulation_start_equity: float = Field(default=50.0, ge=1, le=10_000_000)
    dynamic_protection_enabled: bool = True
    dynamic_protection_runtime_enabled: bool = True
    runtime_stop_management_enabled: bool = True
    runtime_stop_management_min_interval_seconds: int = Field(default=30, ge=5, le=3600)
    runtime_stop_management_min_improvement_atr: float = Field(default=0.10, ge=0, le=10)
    dynamic_protection_runtime_trade_enabled: bool = False
    protection_audit_enabled: bool = True
    protection_audit_auto_repair_enabled: bool = True
    protection_audit_rebuild_invalid_enabled: bool = True
    protection_audit_log_throttle_seconds: int = Field(default=60, ge=0, le=3600)
    protection_audit_fallback_stop_pct: float = Field(default=0.9, ge=0.05, le=20)
    protection_audit_fallback_take_profit_pct: float = Field(default=1.2, ge=0.05, le=50)
    runtime_protection_max_hold_bars: int = Field(default=12, ge=1, le=500)
    protection_fast_invalid_seconds: int = Field(default=90, ge=0, le=3600)
    protection_fast_invalid_atr: float = Field(default=0.35, ge=0, le=10)
    protection_break_even_trigger_atr: float = Field(default=0.55, ge=0, le=20)
    protection_break_even_buffer_pct: float = Field(default=0.08, ge=0, le=5)
    protection_trailing_trigger_atr: float = Field(default=0.9, ge=0, le=30)
    protection_trailing_distance_atr: float = Field(default=0.55, ge=0, le=20)
    protection_min_profit_after_cost_pct: float = Field(default=0.08, ge=0, le=10)
    growth_mode: str = "balanced"
    risk_warning_equity: float = Field(default=30.0, ge=0)
    hard_stop_equity: float = Field(default=5.0, ge=0)
    hard_stop_recovery_equity: float = Field(default=5.5, ge=0)
    tournament_stop_equity: float = Field(default=5.0, ge=0)
    shadow_trading_enabled: bool = True
    shadow_min_candidate_score: float = Field(default=70.0, ge=0, le=300)
    shadow_dedupe_minutes: int = Field(default=10, ge=1, le=1440)
    shadow_max_hold_minutes: int = Field(default=120, ge=1, le=10080)
    shadow_reference_notional_usdt: float = Field(default=20.0, ge=1, le=1_000_000)
    shadow_round_trip_cost_pct: float = Field(default=0.12, ge=0, le=10)
    shadow_stream_max_age_seconds: int = Field(default=20, ge=1, le=300)
    shadow_stream_symbols_limit: int = Field(default=100, ge=1, le=500)
    xmom_shadow_enabled: bool = True
    xmom_shadow_min_delay_seconds: int = Field(default=60, ge=0, le=600)
    xmom_shadow_max_delay_seconds: int = Field(default=150, ge=1, le=900)
    xmom_shadow_stream_max_age_seconds: int = Field(default=20, ge=1, le=300)
    xmom_shadow_min_universe: int = Field(default=60, ge=10, le=250)
    xmom_shadow_min_24h_volume_usdt: float = Field(default=5_000_000, ge=0)
    xmom_shadow_min_onboard_age_days: int = Field(default=30, ge=0, le=3650)
    xmom_shadow_atr_period: int = Field(default=24, ge=5, le=100)
    xmom_shadow_stop_atr: float = Field(default=1.2, ge=0.1, le=10)
    xmom_shadow_reward_r: float = Field(default=1.8, ge=0.1, le=10)
    xmom_shadow_max_stop_pct: float = Field(default=15.0, ge=0.1, le=30)
    xmom_shadow_max_hold_hours: int = Field(default=12, ge=1, le=168)
    xmom_shadow_episode_minutes: int = Field(default=360, ge=30, le=1440)
    adaptive_30d_shadow_enabled: bool = True
    adaptive_30d_shadow_utc_hour: int = Field(default=0, ge=0, le=23)
    adaptive_30d_shadow_minute_start: int = Field(default=2, ge=0, le=59)
    adaptive_30d_shadow_minute_end: int = Field(default=45, ge=0, le=59)
    adaptive_30d_shadow_stream_max_age_seconds: int = Field(default=30, ge=1, le=300)
    adaptive_30d_shadow_symbol_limit: int = Field(default=150, ge=60, le=250)
    adaptive_30d_shadow_min_universe: int = Field(default=60, ge=10, le=250)
    adaptive_30d_shadow_min_24h_volume_usdt: float = Field(default=20_000_000, ge=0)
    adaptive_30d_shadow_min_onboard_age_days: int = Field(default=45, ge=0, le=3650)
    adaptive_30d_shadow_min_abs_breadth_pct: float = Field(default=2.0, ge=0, le=100)
    adaptive_30d_shadow_max_abs_breadth_pct: float = Field(default=10.0, ge=0, le=100)
    adaptive_30d_shadow_stop_atr: float = Field(default=3.0, ge=0.1, le=10)
    adaptive_30d_shadow_reward_r: float = Field(default=3.0, ge=0.1, le=10)
    adaptive_30d_shadow_max_stop_pct: float = Field(default=15.0, ge=0.1, le=30)
    adaptive_30d_shadow_max_hold_hours: int = Field(default=168, ge=1, le=720)
    adaptive_30d_live_enabled: bool = False
    adaptive_30d_live_new_entries_enabled: bool = True
    adaptive_30d_live_manage_existing_enabled: bool = True
    adaptive_30d_live_entry_window_hours: int = Field(default=2, ge=1, le=6)
    adaptive_30d_live_direction_window: int = Field(default=8, ge=3, le=50)
    adaptive_30d_live_direction_min_trades: int = Field(default=3, ge=3, le=50)
    adaptive_30d_live_direction_min_profit_factor: float = Field(default=1.25, ge=0, le=10)
    adaptive_30d_live_risk_pct: float = Field(default=20.0, ge=0.01, le=20)
    adaptive_30d_live_leverage: int = Field(default=2, ge=1, le=5)
    adaptive_30d_live_margin_pct: float = Field(default=90.0, ge=5, le=95)
    adaptive_30d_live_stop_atr: float = Field(default=2.5, ge=0.1, le=10)
    adaptive_30d_live_reward_r: float = Field(default=3.5, ge=0.1, le=10)
    adaptive_30d_live_max_stop_pct: float = Field(default=12.0, ge=0.1, le=30)
    adaptive_30d_live_risk_tier_enabled: bool = False
    adaptive_30d_live_risk_tier_equity: float = Field(default=30.0, ge=1, le=10000)
    adaptive_30d_live_risk_tier2_pct: float = Field(default=20.0, ge=0.01, le=22)
    adaptive_30d_live_min_equity_usdt: float = Field(default=10.0, ge=5, le=10000)
    adaptive_30d_live_hard_stop_reserve_usdt: float = Field(default=0.50, ge=0, le=100)
    adaptive_30d_live_bnb_fallback_enabled: bool = True
    s0_event_live_enabled: bool = False
    s0_event_s_grade_min_score: float = Field(default=82.0, ge=0, le=100)
    s0_event_s_grade_max_account_risk_pct: float = Field(default=50.0, ge=1, le=50)
    s0_event_s_grade_max_leverage: int = Field(default=15, ge=1, le=20)
    s0_event_margin_pct: float = Field(default=97.0, ge=1, le=99)
    s0_event_stop_pct: float = Field(default=3.0, ge=0.2, le=20)
    s0_event_take_profit_r: float = Field(default=2.0, ge=0.5, le=10)
    s0_event_max_hold_seconds: int = Field(default=21600, ge=60, le=86400)
    s0_event_max_age_seconds: int = Field(default=300, ge=30, le=3600)
    s0_event_hard_stop_reserve_usdt: float = Field(default=0.25, ge=0, le=100)
    s0_event_min_liquidation_buffer_pct: float = Field(default=2.0, ge=0, le=30)
    market_tsmom_shadow_enabled: bool = True
    market_tsmom_shadow_utc_hour: int = Field(default=0, ge=0, le=23)
    market_tsmom_shadow_minute_start: int = Field(default=3, ge=0, le=59)
    market_tsmom_shadow_minute_end: int = Field(default=50, ge=0, le=59)
    market_tsmom_shadow_min_24h_volume_usdt: float = Field(default=20_000_000, ge=0)
    market_tsmom_shadow_min_onboard_age_days: int = Field(default=90, ge=0, le=3650)
    market_tsmom_shadow_stream_max_age_seconds: int = Field(default=30, ge=1, le=300)
    market_tsmom_shadow_prefetch_symbols: int = Field(default=40, ge=20, le=250)
    market_tsmom_shadow_min_prefetch_symbols: int = Field(default=25, ge=20, le=250)
    market_tsmom_shadow_market_symbols: int = Field(default=20, ge=10, le=100)
    market_tsmom_shadow_top_third_threshold_pct: float = Field(default=10.65, ge=-100, le=1000)
    market_tsmom_shadow_stop_pct: float = Field(default=15.0, ge=0.1, le=50)
    market_tsmom_shadow_atr_multiple: float = Field(default=3.0, ge=0.1, le=10)
    market_tsmom_shadow_max_hold_hours: int = Field(default=480, ge=1, le=720)
    market_tsmom_shadow_reference_risk_pct: float = Field(default=20.0, ge=0.01, le=30)
    market_tsmom_shadow_execution_equity_usdt: float = Field(default=15.153, ge=5, le=10000)
    market_tsmom_live_enabled: bool = False
    market_tsmom_live_new_entries_enabled: bool = True
    market_tsmom_bnb_stop_pct: float = Field(default=15.0, ge=1, le=30)
    market_tsmom_bnb_max_hold_hours: int = Field(default=120, ge=24, le=240)
    market_tsmom_bnb_entry_window_hours: int = Field(default=2, ge=1, le=6)
    market_tsmom_live_risk_pct: float = Field(default=20.0, ge=0.01, le=30)
    market_tsmom_live_leverage: int = Field(default=2, ge=1, le=3)
    market_tsmom_live_margin_pct: float = Field(default=90.0, ge=5, le=95)
    market_tsmom_live_min_equity_usdt: float = Field(default=10.0, ge=5, le=10000)
    market_tsmom_live_hard_stop_reserve_usdt: float = Field(default=0.50, ge=0, le=100)
    market_tsmom_execution_fallback_enabled: bool = True
    market_tsmom_bootstrap_current_day_enabled: bool = True
    market_tsmom_frequency_challenger_enabled: bool = True
    market_tsmom_frequency_challenger_stop_pct: float = Field(default=15.0, ge=1, le=30)
    market_tsmom_frequency_challenger_max_hold_hours: int = Field(default=72, ge=24, le=240)
    auto_risk_by_equity: bool = True
    stage_routing_enabled: bool = True
    stage_manual_mode: str = "auto"
    stage_manual_until: str = ""
    stage_manual_default_hours: float = Field(default=6.0, ge=0, le=168)
    stage_switch_up_buffer_pct: float = Field(default=5.0, ge=0, le=100)
    stage_switch_down_buffer_pct: float = Field(default=10.0, ge=0, le=100)
    stage_switch_confirmations: int = Field(default=3, ge=1, le=100)
    stage_s0_risk_pct: float = Field(default=30.0, ge=0.01, le=100)
    stage_s0_margin_pct: float = Field(default=90.0, ge=1, le=100)
    stage_s0_max_leverage: float = Field(default=10.0, ge=1, le=50)
    stage_s0_max_open_positions: int = Field(default=1, ge=1, le=20)
    stage_s0_daily_loss_limit_pct: float = Field(default=30.0, ge=0.1, le=100)
    stage_s0_daily_loss_stop_enabled: bool = False
    stage_s0_daily_profit_lock_enabled: bool = True
    stage_s0_daily_profit_target_pct: float = Field(default=50.0, ge=1, le=500)
    stage_s1_risk_pct: float = Field(default=7.0, ge=0.01, le=100)
    stage_s1_margin_pct: float = Field(default=85.0, ge=1, le=100)
    stage_s1_max_leverage: float = Field(default=5.0, ge=1, le=50)
    stage_s1_max_open_positions: int = Field(default=1, ge=1, le=20)
    stage_s1_daily_loss_limit_pct: float = Field(default=25.0, ge=0.1, le=100)
    stage_s2_risk_pct: float = Field(default=3.0, ge=0.01, le=100)
    stage_s2_margin_pct: float = Field(default=60.0, ge=1, le=100)
    stage_s2_max_leverage: float = Field(default=4.0, ge=1, le=50)
    stage_s2_max_open_positions: int = Field(default=2, ge=1, le=20)
    stage_s2_daily_loss_limit_pct: float = Field(default=12.0, ge=0.1, le=100)
    stage_s3_risk_pct: float = Field(default=0.35, ge=0.01, le=100)
    stage_s3_margin_pct: float = Field(default=25.0, ge=1, le=100)
    stage_s3_max_leverage: float = Field(default=3.0, ge=1, le=50)
    stage_s3_max_open_positions: int = Field(default=4, ge=1, le=20)
    stage_s3_daily_loss_limit_pct: float = Field(default=3.0, ge=0.1, le=100)
    stage_s4_risk_pct: float = Field(default=0.2, ge=0.01, le=100)
    stage_s4_margin_pct: float = Field(default=15.0, ge=1, le=100)
    stage_s4_max_leverage: float = Field(default=2.0, ge=1, le=50)
    stage_s4_max_open_positions: int = Field(default=8, ge=1, le=20)
    stage_s4_daily_loss_limit_pct: float = Field(default=1.5, ge=0.1, le=100)
    stage_s4_scalp_overlay_enabled: bool = True
    stage_s4_scalp_risk_pct: float = Field(default=0.1, ge=0.01, le=10)
    stage_s4_scalp_margin_pct: float = Field(default=5.0, ge=1, le=50)
    stage_s4_scalp_daily_loss_limit_pct: float = Field(default=1.0, ge=0.1, le=20)
    risk_per_trade_pct: float = Field(default=1.0, ge=0.1, le=25)
    attack_risk_per_trade_pct: float = Field(default=5.0, ge=0.1, le=25)
    tournament_risk_per_trade_pct: float = Field(default=15.0, ge=0.1, le=50)
    tournament_sprint_risk_per_trade_pct: float = Field(default=18.0, ge=0.1, le=60)
    extreme_sprint_enabled: bool = False
    extreme_sprint_confirmation: str = ""
    extreme_sprint_auto_under_equity: float = Field(default=10000.0, ge=0)
    extreme_sprint_risk_per_trade_pct: float = Field(default=28.0, ge=0.1, le=100)
    extreme_sprint_max_leverage: float = Field(default=8, ge=1, le=50)
    extreme_sprint_max_symbol_margin_pct: float = Field(default=98.0, ge=1, le=100)
    extreme_sprint_recent_days: int = Field(default=2, ge=1, le=14)
    extreme_sprint_interval: str = "5m"
    extreme_sprint_standard_min_score: float = Field(default=88.0, ge=0, le=200)
    extreme_sprint_preemptive_min_score: float = Field(default=72.0, ge=0, le=200)
    extreme_sprint_momentum_min_score: float = Field(default=68.0, ge=0, le=200)
    extreme_sprint_min_expected_profit_cost_ratio: float = Field(default=1.1, ge=0, le=50)
    extreme_sprint_min_expected_profit_pct: float = Field(default=0.18, ge=0, le=20)
    extreme_sprint_standard_stop_atr: float = Field(default=0.85, ge=0.1, le=10)
    extreme_sprint_standard_take_profit_atr: float = Field(default=1.8, ge=0.1, le=20)
    extreme_sprint_standard_max_hold_bars: int = Field(default=10, ge=1, le=100)
    extreme_sprint_preemptive_stop_atr: float = Field(default=0.7, ge=0.1, le=10)
    extreme_sprint_preemptive_take_profit_atr: float = Field(default=1.15, ge=0.1, le=20)
    extreme_sprint_preemptive_max_hold_bars: int = Field(default=5, ge=1, le=100)
    extreme_sprint_momentum_stop_atr: float = Field(default=0.75, ge=0.1, le=10)
    extreme_sprint_momentum_take_profit_atr: float = Field(default=1.35, ge=0.1, le=20)
    extreme_sprint_momentum_max_hold_bars: int = Field(default=6, ge=1, le=100)
    extreme_sprint_high_score: float = Field(default=110.0, ge=0, le=300)
    extreme_sprint_super_score: float = Field(default=135.0, ge=0, le=300)
    extreme_sprint_high_risk_multiplier: float = Field(default=1.35, ge=0.1, le=5)
    extreme_sprint_super_risk_multiplier: float = Field(default=1.75, ge=0.1, le=5)
    extreme_scalp_enabled: bool = True
    extreme_scalp_high_score: float = Field(default=122.0, ge=0, le=300)
    extreme_scalp_super_score: float = Field(default=145.0, ge=0, le=300)
    extreme_scalp_min_quality_score: float = Field(default=72.0, ge=0, le=100)
    extreme_scalp_min_cost_ratio: float = Field(default=12.0, ge=0, le=200)
    extreme_scalp_min_depth_notional_usdt: float = Field(default=20_000.0, ge=0)
    extreme_scalp_high_risk_multiplier: float = Field(default=1.25, ge=0.1, le=5)
    extreme_scalp_super_risk_multiplier: float = Field(default=1.55, ge=0.1, le=5)
    extreme_scalp_max_risk_pct: float = Field(default=18.0, ge=0.1, le=100)
    extreme_scalp_stop_atr: float = Field(default=0.55, ge=0.05, le=10)
    extreme_scalp_take_profit_atr: float = Field(default=0.75, ge=0.05, le=20)
    extreme_scalp_max_hold_bars: int = Field(default=2, ge=1, le=100)
    extreme_sprint_max_consecutive_losses: int = Field(default=5, ge=1, le=20)
    extreme_sprint_daily_loss_limit_pct: float = Field(default=50.0, ge=0.1, le=95)
    yolo_scalp_enabled: bool = False
    yolo_scalp_confirmation: str = ""
    yolo_scalp_auto_under_equity: float = Field(default=300.0, ge=0)
    yolo_scalp_interval: str = "5m"
    yolo_scalp_recent_days: int = Field(default=1, ge=1, le=7)
    yolo_scalp_risk_per_trade_pct: float = Field(default=55.0, ge=0.1, le=100)
    yolo_scalp_max_leverage: float = Field(default=10, ge=1, le=50)
    yolo_scalp_max_symbol_margin_pct: float = Field(default=100.0, ge=1, le=100)
    yolo_scalp_daily_loss_limit_pct: float = Field(default=65.0, ge=0.1, le=95)
    yolo_scalp_max_open_positions: int = Field(default=1, ge=1, le=3)
    yolo_scalp_standard_min_score: float = Field(default=72.0, ge=0, le=300)
    yolo_scalp_preemptive_min_score: float = Field(default=58.0, ge=0, le=300)
    yolo_scalp_momentum_min_score: float = Field(default=54.0, ge=0, le=300)
    yolo_scalp_preemptive_max_distance_pct: float = Field(default=0.75, ge=0, le=10)
    yolo_scalp_min_expected_profit_cost_ratio: float = Field(default=0.85, ge=0, le=100)
    yolo_scalp_min_expected_profit_pct: float = Field(default=0.10, ge=0, le=20)
    yolo_scalp_standard_stop_atr: float = Field(default=0.38, ge=0.05, le=10)
    yolo_scalp_standard_take_profit_atr: float = Field(default=0.55, ge=0.05, le=20)
    yolo_scalp_standard_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_preemptive_stop_atr: float = Field(default=0.32, ge=0.05, le=10)
    yolo_scalp_preemptive_take_profit_atr: float = Field(default=0.48, ge=0.05, le=20)
    yolo_scalp_preemptive_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_momentum_stop_atr: float = Field(default=0.35, ge=0.05, le=10)
    yolo_scalp_momentum_take_profit_atr: float = Field(default=0.60, ge=0.05, le=20)
    yolo_scalp_momentum_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_probe_stop_atr: float = Field(default=0.40, ge=0.05, le=10)
    yolo_scalp_probe_take_profit_atr: float = Field(default=0.55, ge=0.05, le=20)
    yolo_scalp_probe_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_weak_probe_stop_atr: float = Field(default=0.34, ge=0.05, le=10)
    yolo_scalp_weak_probe_take_profit_atr: float = Field(default=0.48, ge=0.05, le=20)
    yolo_scalp_weak_probe_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_high_score: float = Field(default=95.0, ge=0, le=300)
    yolo_scalp_super_score: float = Field(default=118.0, ge=0, le=300)
    yolo_scalp_high_risk_multiplier: float = Field(default=1.35, ge=0.1, le=5)
    yolo_scalp_super_risk_multiplier: float = Field(default=1.80, ge=0.1, le=5)
    yolo_scalp_standard_min_risk_pct: float = Field(default=35.0, ge=0.1, le=100)
    yolo_scalp_standard_max_risk_pct: float = Field(default=75.0, ge=0.1, le=100)
    yolo_scalp_preemptive_min_risk_pct: float = Field(default=28.0, ge=0.1, le=100)
    yolo_scalp_preemptive_max_risk_pct: float = Field(default=65.0, ge=0.1, le=100)
    yolo_scalp_firecracker_min_risk_pct: float = Field(default=30.0, ge=0.1, le=100)
    yolo_scalp_firecracker_max_risk_pct: float = Field(default=70.0, ge=0.1, le=100)
    yolo_scalp_weak_probe_min_risk_pct: float = Field(default=8.0, ge=0.1, le=100)
    yolo_scalp_weak_probe_max_risk_pct: float = Field(default=25.0, ge=0.1, le=100)
    yolo_scalp_loss_probe_max_risk_pct: float = Field(default=12.0, ge=0.1, le=100)
    yolo_scalp_loss_probe_risk_multiplier: float = Field(default=0.75, ge=0.01, le=1)
    yolo_scalp_min_order_lift_enabled: bool = True
    yolo_scalp_effective_min_order_notional_usdt: float = Field(default=5.0, ge=0)
    yolo_scalp_min_order_lift_max_loss_pct: float = Field(default=8.0, ge=0.1, le=100)
    yolo_scalp_min_order_lift_min_cost_ratio: float = Field(default=3.0, ge=0, le=200)
    yolo_scalp_min_order_lift_min_net_profit_usdt: float = Field(default=0.03, ge=0, le=100)
    yolo_scalp_min_quality_score: float = Field(default=58.0, ge=0, le=100)
    yolo_scalp_min_cost_ratio: float = Field(default=4.0, ge=0, le=200)
    yolo_scalp_min_depth_notional_usdt: float = Field(default=1000.0, ge=0)
    yolo_scalp_max_risk_pct: float = Field(default=75.0, ge=0.1, le=100)
    yolo_scalp_stop_atr: float = Field(default=0.32, ge=0.05, le=10)
    yolo_scalp_take_profit_atr: float = Field(default=0.48, ge=0.05, le=20)
    yolo_scalp_max_hold_bars: int = Field(default=2, ge=1, le=100)
    yolo_scalp_orderbook_engine_enabled: bool = True
    yolo_scalp_orderbook_only_enabled: bool = True
    yolo_scalp_orderbook_max_spread_pct: float = Field(default=0.08, ge=0, le=5)
    yolo_scalp_orderbook_min_depth_notional_usdt: float = Field(default=1000.0, ge=0)
    yolo_scalp_orderbook_probe_min_depth_notional_usdt: float = Field(default=300.0, ge=0)
    yolo_scalp_orderbook_min_imbalance: float = Field(default=0.05, ge=0, le=1)
    yolo_scalp_orderbook_strong_imbalance: float = Field(default=0.14, ge=0, le=1)
    yolo_scalp_orderbook_allow_strong_imbalance_direction_probe: bool = True
    yolo_scalp_orderbook_event_max_age_seconds: int = Field(default=45, ge=1, le=600)
    yolo_scalp_stream_max_age_seconds: int = Field(default=12, ge=1, le=120)
    yolo_scalp_orderbook_min_1m_move_pct: float = Field(default=0.08, ge=0, le=20)
    yolo_scalp_orderbook_min_1m_quote_volume_usdt: float = Field(default=25000.0, ge=0)
    yolo_scalp_orderbook_min_profit_cost_ratio: float = Field(default=1.05, ge=0, le=100)
    yolo_scalp_orderbook_min_net_profit_pct: float = Field(default=0.025, ge=0, le=20)
    yolo_scalp_orderbook_move_profit_capture: float = Field(default=0.45, ge=0, le=5)
    yolo_scalp_orderbook_atr_profit_capture: float = Field(default=0.16, ge=0, le=5)
    yolo_scalp_orderbook_target_net_profit_pct: float = Field(default=0.06, ge=0, le=20)
    yolo_scalp_orderbook_min_take_profit_pct: float = Field(default=0.14, ge=0, le=20)
    yolo_scalp_orderbook_stop_pct: float = Field(default=0.20, ge=0.01, le=20)
    yolo_scalp_orderbook_max_hold_seconds: int = Field(default=120, ge=10, le=3600)
    yolo_scalp_orderbook_runtime_exit_enabled: bool = True
    yolo_scalp_orderbook_exit_spread_multiplier: float = Field(default=2.0, ge=1, le=20)
    yolo_scalp_orderbook_exit_reverse_imbalance: float = Field(default=0.04, ge=0, le=1)
    yolo_scalp_orderbook_impact_min_risk_pct: float = Field(default=45.0, ge=0.1, le=100)
    yolo_scalp_orderbook_impact_max_risk_pct: float = Field(default=85.0, ge=0.1, le=100)
    yolo_scalp_orderbook_volume_min_risk_pct: float = Field(default=35.0, ge=0.1, le=100)
    yolo_scalp_orderbook_volume_max_risk_pct: float = Field(default=75.0, ge=0.1, le=100)
    yolo_scalp_orderbook_probe_min_risk_pct: float = Field(default=18.0, ge=0.1, le=100)
    yolo_scalp_orderbook_probe_max_risk_pct: float = Field(default=40.0, ge=0.1, le=100)
    yolo_scalp_credit_experiment_enabled: bool = True
    yolo_scalp_strategy_credit_enabled: bool = True
    yolo_scalp_legacy_credit_soft_multiplier: float = Field(default=1.0, ge=0.01, le=1)
    yolo_scalp_legacy_credit_soft_score_threshold: float = Field(default=30.0, ge=0, le=100)
    yolo_scalp_legacy_credit_soft_penalty_multiplier: float = Field(default=1.0, ge=0.01, le=1)
    scalp_credit_quick_stop_seconds: int = Field(default=35, ge=5, le=300)
    scalp_credit_win_reward: float = Field(default=5.0, ge=0, le=30)
    scalp_credit_loss_penalty: float = Field(default=7.5, ge=0, le=40)
    scalp_credit_consecutive_loss_penalty: float = Field(default=12.0, ge=0, le=60)
    scalp_credit_fee_drag_penalty: float = Field(default=4.5, ge=0, le=30)
    scalp_credit_penalty_cooldown_hours: float = Field(default=1.0, ge=0, le=24)
    scalp_credit_recovery_interval_hours: float = Field(default=3.0, ge=0.1, le=48)
    scalp_credit_recovery_points: float = Field(default=4.0, ge=0, le=30)
    extreme_credit_quick_stop_seconds: int = Field(default=300, ge=30, le=3600)
    extreme_credit_win_reward: float = Field(default=5.0, ge=0, le=30)
    extreme_credit_loss_penalty: float = Field(default=7.0, ge=0, le=40)
    extreme_credit_consecutive_loss_penalty: float = Field(default=10.0, ge=0, le=60)
    extreme_credit_fee_drag_penalty: float = Field(default=3.0, ge=0, le=30)
    extreme_credit_penalty_cooldown_hours: float = Field(default=2.0, ge=0, le=48)
    extreme_credit_recovery_interval_hours: float = Field(default=6.0, ge=0.1, le=96)
    extreme_credit_recovery_points: float = Field(default=3.0, ge=0, le=30)
    opportunity_v3_enabled: bool = True
    opportunity_v3_realtime_backtest_enabled: bool = False
    opportunity_v3_donchian_lookbacks: list[int] = Field(default_factory=lambda: [12, 24, 48])
    opportunity_v3_volume_acceleration_min: float = Field(default=1.05, ge=0, le=20)
    opportunity_v3_prebreakout_distance_atr: float = Field(default=0.35, ge=0, le=10)
    opportunity_v3_panic_breadth: float = Field(default=0.20, ge=0, le=1)
    opportunity_v3_trend_breadth: float = Field(default=0.62, ge=0, le=1)
    opportunity_v3_market_trend_move_pct: float = Field(default=0.8, ge=0, le=100)
    opportunity_v3_rotation_dispersion_pct: float = Field(default=7.0, ge=0, le=200)
    opportunity_v3_quiet_median_abs_pct: float = Field(default=1.8, ge=0, le=100)
    execution_max_spread_pct: float = Field(default=0.10, ge=0, le=5)
    execution_min_depth_notional_usdt: float = Field(default=5_000.0, ge=0)
    opportunity_v3_max_spread_pct: float = Field(default=0.10, ge=0, le=5)
    opportunity_v3_min_depth_notional_usdt: float = Field(default=5_000.0, ge=0)
    opportunity_v3_stream_depth_max_age_seconds: int = Field(default=8, ge=1, le=60)
    opportunity_v3_long_strength_floor: float = Field(default=0.58, ge=0, le=1)
    opportunity_v3_short_strength_floor: float = Field(default=0.68, ge=0, le=1)
    opportunity_v3_event_fresh_seconds: int = Field(default=90, ge=1, le=3600)
    opportunity_v3_a_plus_score: float = Field(default=82.0, ge=0, le=100)
    opportunity_v3_a_score: float = Field(default=70.0, ge=0, le=100)
    opportunity_v3_b_score: float = Field(default=58.0, ge=0, le=100)
    opportunity_v3_a_plus_min_cost_ratio: float = Field(default=3.0, ge=0, le=100)
    opportunity_v3_a_min_cost_ratio: float = Field(default=2.0, ge=0, le=100)
    opportunity_v3_b_min_cost_ratio: float = Field(default=1.35, ge=0, le=100)
    opportunity_v3_b_live_enabled: bool = False
    opportunity_v3_basis_confirm_pct: float = Field(default=0.02, ge=0, le=10)
    opportunity_v3_basis_divergence_pct: float = Field(default=0.08, ge=0, le=10)
    opportunity_v3_basis_confirm_bonus: float = Field(default=2.0, ge=0, le=20)
    opportunity_v3_basis_divergence_penalty: float = Field(default=3.0, ge=0, le=30)
    opportunity_v3_canary_bypass_enabled: bool = False
    opportunity_v3_canary_risk_multiplier: float = Field(default=0.25, ge=0.01, le=1)
    opportunity_v3_strategy_version: str = "v3.2"
    opportunity_v3_calibration_enabled: bool = False
    opportunity_v3_calibration_live_min_trades: int = Field(default=30, ge=1, le=10000)
    opportunity_v3_calibration_shadow_min_trades: int = Field(default=70, ge=1, le=10000)
    opportunity_v3_calibration_lookback_days: float = Field(default=30, ge=1, le=3650)
    opportunity_v3_calibration_cache_seconds: int = Field(default=60, ge=1, le=3600)
    opportunity_v3_calibration_max_live_trades: int = Field(default=500, ge=1, le=10000)
    opportunity_v3_calibration_max_shadow_trades: int = Field(default=1500, ge=1, le=50000)
    opportunity_v3_calibration_max_strategy_runs: int = Field(default=2500, ge=100, le=100000)
    opportunity_v3_calibration_min_profit_factor: float = Field(default=1.20, ge=0, le=100)
    opportunity_v3_calibration_min_net_expectancy_pct: float = Field(default=0.02, ge=-100, le=100)
    opportunity_v3_calibration_negative_live_trades: int = Field(default=10, ge=1, le=10000)
    opportunity_v3_calibration_negative_profit_factor: float = Field(default=0.70, ge=0, le=100)
    opportunity_v3_unvalidated_a_plus_risk_multiplier: float = Field(default=0.65, ge=0, le=1)
    opportunity_v3_block_countertrend: bool = True
    opportunity_v3_panic_requires_pullback: bool = True
    opportunity_v3_prebreakout_live_enabled: bool = False
    opportunity_v3_max_breakout_extension_atr: float = Field(default=0.65, ge=0, le=20)
    opportunity_v3_max_entry_impulse_atr: float = Field(default=1.35, ge=0, le=20)
    opportunity_v3_medium_confirmation_enabled: bool = True
    opportunity_v3_a_plus_requires_medium_alignment: bool = True
    opportunity_v3_min_medium_path_efficiency: float = Field(default=0.16, ge=0, le=1)
    opportunity_v3_credit_min_multiplier: float = Field(default=0.80, ge=0.01, le=2)
    opportunity_v3_credit_cooldown_min_multiplier: float = Field(default=0.35, ge=0.01, le=1)
    opportunity_v3_credit_max_multiplier: float = Field(default=1.20, ge=0.1, le=2)
    opportunity_v31_challenger_enabled: bool = False
    opportunity_v31_medium_pool_limit: int = Field(default=12, ge=1, le=50)
    opportunity_v31_bar_cache_seconds: int = Field(default=600, ge=60, le=3600)
    opportunity_v31_min_path_efficiency: float = Field(default=0.18, ge=0, le=1)
    opportunity_v31_shadow_min_score: float = Field(default=68.0, ge=0, le=100)
    opportunity_v31_min_closed_trades: int = Field(default=100, ge=10, le=10000)
    opportunity_v31_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    opportunity_v31_live_enabled: bool = False
    opportunity_v33_challenger_enabled: bool = False
    opportunity_v33_strategy_version: str = "v3.3-candidate"
    opportunity_v33_min_score: float = Field(default=68.0, ge=0, le=100)
    opportunity_v33_min_cost_ratio: float = Field(default=2.5, ge=0, le=100)
    opportunity_v33_min_medium_path_efficiency: float = Field(default=0.18, ge=0, le=1)
    opportunity_v33_pullback_min_flow: float = Field(default=0.50, ge=0, le=1)
    opportunity_v33_pullback_min_volume_acceleration: float = Field(default=0.90, ge=0, le=100)
    opportunity_v33_breakout_min_score: float = Field(default=70.0, ge=0, le=100)
    opportunity_v33_prebreakout_min_score: float = Field(default=68.0, ge=0, le=100)
    opportunity_v33_panic_pullback_only: bool = True
    opportunity_v33_momentum_shadow_enabled: bool = True
    opportunity_v33_pullback_take_profit_atr: float = Field(default=2.4, ge=0.1, le=20)
    opportunity_v33_pullback_max_hold_bars: int = Field(default=18, ge=1, le=200)
    opportunity_v33_validation_min_trades: int = Field(default=300, ge=10, le=100000)
    opportunity_v33_validation_min_hours: float = Field(default=72, ge=1, le=8760)
    opportunity_v33_validation_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    opportunity_v33_validation_min_regimes: int = Field(default=2, ge=1, le=20)
    opportunity_v4_enabled: bool = True
    opportunity_v4_live_enabled: bool = True
    opportunity_v4_strategy_version: str = "v5.4"
    opportunity_v4_evidence_version: str = ""
    s0_moe_shadow_enabled: bool = True
    s0_moe_runtime_model_enabled: bool = False
    s0_moe_model_path: str = ""
    s0_moe_candidate_status_path: str = ""
    s0_moe_shadow_candidate_limit: int = Field(default=25, ge=1, le=50)
    s0_moe_online_window_hours: float = Field(default=24.0, ge=1, le=720)
    s0_moe_retrain_min_selected_closes: int = Field(default=200, ge=20, le=100000)
    s0_moe_retrain_min_regimes: int = Field(default=2, ge=1, le=20)
    opportunity_v472_pullback_min_cost_ratio: float = Field(default=1.8, ge=0, le=1000)
    opportunity_v472_breakout_min_cost_ratio: float = Field(default=2.3, ge=0, le=1000)
    opportunity_v472_momentum_min_cost_ratio: float = Field(default=2.3, ge=0, le=1000)
    opportunity_v472_prebreakout_min_cost_ratio: float = Field(default=2.3, ge=0, le=1000)
    opportunity_v472_pullback_max_hold_bars: int = Field(default=4, ge=1, le=100)
    opportunity_v472_episode_dedupe_minutes: int = Field(default=45, ge=0, le=1440)
    opportunity_v472_symbol_event_window_hours: float = Field(default=6.0, ge=0.25, le=168)
    opportunity_v472_symbol_max_events_per_window: int = Field(default=3, ge=1, le=100)
    opportunity_v473_min_expected_net_pct: float = Field(default=0.20, ge=-100, le=100)
    opportunity_v473_min_lower_expectancy_pct: float = Field(default=0.09, ge=-100, le=100)
    opportunity_v473_stagnation_seconds: int = Field(default=180, ge=30, le=3600)
    opportunity_v473_stagnation_min_profit_pct: float = Field(default=0.12, ge=-100, le=100)
    opportunity_v473_max_hold_seconds: int = Field(default=480, ge=60, le=7200)
    opportunity_v473_fast_invalid_seconds: int = Field(default=120, ge=0, le=1800)
    opportunity_v410_seed_version: str = "v4.9"
    opportunity_v410_global_regime_enabled: bool = True
    opportunity_v410_global_smart_flow_enabled: bool = True
    opportunity_v410_direction_aligned_multiplier: float = Field(default=1.05, ge=0.5, le=1.2)
    opportunity_v410_direction_countertrend_multiplier: float = Field(default=0.90, ge=0.5, le=1.0)
    opportunity_v49_global_adaptive_enabled: bool = True
    opportunity_v49_global_window_hours: float = Field(default=24.0, ge=1, le=168)
    opportunity_v49_global_min_shadow_trades: int = Field(default=20, ge=5, le=10000)
    opportunity_v49_global_min_live_trades: int = Field(default=8, ge=2, le=10000)
    opportunity_v49_global_target_live_trades: int = Field(default=12, ge=2, le=10000)
    opportunity_v49_global_min_symbols: int = Field(default=3, ge=1, le=100)
    opportunity_v49_global_min_regimes: int = Field(default=2, ge=1, le=20)
    opportunity_v49_global_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    opportunity_v49_global_min_net_pct: float = Field(default=0.0, ge=-100, le=100)
    opportunity_v49_global_update_hours: float = Field(default=2.0, ge=0.5, le=24)
    opportunity_v49_global_max_step: float = Field(default=0.05, ge=0.01, le=0.2)
    opportunity_v49_global_min_multiplier: float = Field(default=0.70, ge=0, le=1)
    opportunity_v49_global_max_multiplier: float = Field(default=1.10, ge=0, le=2)
    opportunity_v49_global_positive_relaxation_step: float = Field(default=0.03, ge=0, le=0.2)
    opportunity_v49_global_negative_tightening_step: float = Field(default=0.05, ge=0, le=0.2)
    opportunity_v49_global_min_rank_percentile: float = Field(default=0.65, ge=0, le=1)
    opportunity_v49_global_max_rank_percentile: float = Field(default=0.90, ge=0, le=1)
    opportunity_v49_global_min_quality_score: float = Field(default=52.0, ge=0, le=100)
    opportunity_v49_global_max_quality_score: float = Field(default=70.0, ge=0, le=100)
    opportunity_v49_global_min_expectancy_pct: float = Field(default=0.0, ge=-100, le=100)
    opportunity_v49_global_max_expectancy_pct: float = Field(default=0.20, ge=-100, le=100)
    opportunity_v49_global_min_cost_ratio: float = Field(default=1.35, ge=0, le=100)
    opportunity_v49_global_max_cost_ratio: float = Field(default=2.50, ge=0, le=100)
    opportunity_v49_global_min_confirmations: int = Field(default=3, ge=1, le=5)
    opportunity_v49_global_max_confirmations: int = Field(default=5, ge=1, le=5)
    opportunity_v4_decision_min_rank_percentile: float = Field(default=0.75, ge=0, le=1)
    opportunity_v4_bootstrap_enabled: bool = True
    opportunity_v4_bootstrap_min_rank_percentile: float = Field(default=0.85, ge=0, le=1)
    opportunity_v4_bootstrap_min_quality_score: float = Field(default=58.0, ge=0, le=100)
    opportunity_v4_bootstrap_min_model_expectancy_pct: float = Field(default=0.10, ge=-100, le=100)
    opportunity_v4_bootstrap_risk_multiplier: float = Field(default=0.40, ge=0, le=1)
    opportunity_v4_bootstrap_negative_min_trades: int = Field(default=20, ge=5, le=10000)
    opportunity_v4_bootstrap_negative_profit_factor: float = Field(default=0.75, ge=0, le=100)
    opportunity_v4_validated_risk_multiplier: float = Field(default=1.0, ge=0, le=2)
    opportunity_v41_provisional_risk_multiplier: float = Field(default=0.70, ge=0, le=1)
    v4_credit_score_weight: float = Field(default=0.25, ge=0, le=2)
    v4_credit_min_multiplier: float = Field(default=0.60, ge=0, le=2)
    v4_credit_cooldown_min_multiplier: float = Field(default=0.35, ge=0, le=2)
    v4_credit_max_multiplier: float = Field(default=1.20, ge=0, le=3)
    opportunity_v4_decision_shadow_limit: int = Field(default=3, ge=1, le=50)
    opportunity_v4_exploration_shadow_limit: int = Field(default=6, ge=0, le=100)
    opportunity_v4_control_shadow_limit: int = Field(default=3, ge=0, le=50)
    opportunity_v4_admission_min_trades: int = Field(default=200, ge=10, le=10000)
    opportunity_v4_admission_min_profit_factor: float = Field(default=1.10, ge=0, le=100)
    opportunity_v4_admission_min_lower_expectancy_pct: float = Field(default=0.0, ge=-100, le=100)
    opportunity_v41_validation_min_trades: int = Field(default=500, ge=10, le=100000)
    opportunity_v41_validation_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    opportunity_v41_validation_min_time_blocks: int = Field(default=2, ge=1, le=100)
    opportunity_v41_validation_min_symbols: int = Field(default=3, ge=1, le=10000)
    opportunity_v41_empirical_prior_trades: int = Field(default=40, ge=1, le=10000)
    opportunity_v41_min_expected_net_pct: float = Field(default=0.10, ge=-100, le=100)
    opportunity_v41_min_cost_ratio: float = Field(default=2.0, ge=0, le=1000)
    opportunity_v41_cost_safety_buffer_pct: float = Field(default=0.02, ge=0, le=10)
    opportunity_v41_medium_alignment_required: bool = True
    opportunity_v41_retest_stop_atr: float = Field(default=0.70, ge=0.05, le=20)
    opportunity_v41_retest_take_profit_atr: float = Field(default=1.25, ge=0.05, le=50)
    opportunity_v41_retest_max_hold_bars: int = Field(default=10, ge=1, le=200)
    opportunity_v41_armed_stop_atr: float = Field(default=0.62, ge=0.05, le=20)
    opportunity_v41_armed_take_profit_atr: float = Field(default=1.05, ge=0.05, le=50)
    opportunity_v41_armed_max_hold_bars: int = Field(default=6, ge=1, le=200)
    opportunity_v41_triggered_stop_atr: float = Field(default=0.70, ge=0.05, le=20)
    opportunity_v41_triggered_take_profit_atr: float = Field(default=1.20, ge=0.05, le=50)
    opportunity_v41_triggered_max_hold_bars: int = Field(default=8, ge=1, le=200)
    opportunity_v42_exploration_enabled: bool = True
    opportunity_v42_exploration_min_rank_percentile: float = Field(default=0.75, ge=0, le=1)
    opportunity_v42_exploration_min_quality_score: float = Field(default=55.0, ge=0, le=100)
    opportunity_v42_exploration_min_expected_net_pct: float = Field(default=0.04, ge=-100, le=100)
    opportunity_v42_exploration_min_lower_expectancy_pct: float = Field(default=-0.03, ge=-100, le=100)
    opportunity_v42_exploration_min_cost_ratio: float = Field(default=1.60, ge=0, le=1000)
    opportunity_v42_exploration_min_confirmations: int = Field(default=2, ge=1, le=4)
    opportunity_v42_exploration_risk_multiplier: float = Field(default=0.40, ge=0, le=1)
    opportunity_v43_exploration_enabled: bool = True
    opportunity_v43_exploration_min_rank_percentile: float = Field(default=0.75, ge=0, le=1)
    opportunity_v43_exploration_min_quality_score: float = Field(default=55.0, ge=0, le=100)
    opportunity_v43_exploration_min_expected_net_pct: float = Field(default=0.04, ge=-100, le=100)
    opportunity_v43_exploration_min_lower_expectancy_pct: float = Field(default=-0.03, ge=-100, le=100)
    opportunity_v43_exploration_min_cost_ratio: float = Field(default=1.60, ge=0, le=1000)
    opportunity_v43_exploration_min_confirmations: int = Field(default=2, ge=1, le=4)
    opportunity_v43_exploration_risk_multiplier: float = Field(default=0.40, ge=0, le=1)
    opportunity_v43_hierarchy_prior_trades: int = Field(default=30, ge=1, le=10000)
    opportunity_v43_local_negative_min_trades: int = Field(default=30, ge=5, le=10000)
    opportunity_v43_local_negative_profit_factor: float = Field(default=0.50, ge=0, le=100)
    opportunity_v43_direction_risk_min_trades: int = Field(default=20, ge=5, le=10000)
    opportunity_v43_direction_low_pf: float = Field(default=0.55, ge=0, le=100)
    opportunity_v43_direction_medium_pf: float = Field(default=0.75, ge=0, le=100)
    opportunity_v43_direction_full_pf: float = Field(default=1.0, ge=0, le=100)
    opportunity_v43_direction_low_multiplier: float = Field(default=0.55, ge=0, le=1)
    opportunity_v43_direction_medium_multiplier: float = Field(default=0.70, ge=0, le=1)
    opportunity_v43_direction_caution_multiplier: float = Field(default=0.85, ge=0, le=1)
    opportunity_v43_dynamic_liquidity_enabled: bool = True
    opportunity_v43_min_depth_floor_usdt: float = Field(default=750.0, ge=0, le=10000000)
    opportunity_v43_depth_to_order_multiple: float = Field(default=12.5, ge=1, le=1000)
    opportunity_v43_max_required_depth_usdt: float = Field(default=50_000.0, ge=0, le=100000000)
    opportunity_v43_max_order_book_share_pct: float = Field(default=8.0, ge=0.01, le=100)
    opportunity_v43_episode_dedupe_minutes: int = Field(default=30, ge=1, le=1440)
    opportunity_v43_episode_reset_risk_multiple: float = Field(default=1.0, ge=0.1, le=20)
    opportunity_v431_local_circuit_enabled: bool = True
    opportunity_v431_local_live_loss_streak: int = Field(default=2, ge=1, le=20)
    opportunity_v431_local_block_min_trades: int = Field(default=8, ge=2, le=10000)
    opportunity_v431_local_block_profit_factor: float = Field(default=0.80, ge=0, le=100)
    opportunity_v431_local_restore_min_trades: int = Field(default=8, ge=2, le=10000)
    opportunity_v431_local_restore_min_symbols: int = Field(default=3, ge=1, le=10000)
    opportunity_v431_local_restore_profit_factor: float = Field(default=1.05, ge=0, le=100)
    opportunity_v432_continuous_sizing_enabled: bool = True
    opportunity_v432_confidence_rank_floor: float = Field(default=0.75, ge=0, lt=1)
    opportunity_v432_confidence_lower_cost_floor: float = Field(default=0.50, ge=-100, le=100)
    opportunity_v432_confidence_lower_cost_full: float = Field(default=2.50, ge=-100, le=100)
    opportunity_v432_confidence_cost_ratio_floor: float = Field(default=2.0, ge=0, le=1000)
    opportunity_v432_confidence_cost_ratio_full: float = Field(default=10.0, ge=0, le=1000)
    opportunity_v432_initial_min_risk_pct: float = Field(default=4.0, ge=0.01, le=100)
    opportunity_v432_initial_max_risk_pct: float = Field(default=7.5, ge=0.01, le=100)
    opportunity_v432_add_on_enabled: bool = False
    opportunity_v432_add_on_live_enabled: bool = False
    opportunity_v432_add_on_trigger_atr: float = Field(default=0.55, ge=0.05, le=20)
    opportunity_v432_add_on_min_confidence: float = Field(default=0.75, ge=0, le=1)
    opportunity_v432_add_on_min_lower_cost_multiple: float = Field(default=2.0, ge=-100, le=100)
    opportunity_v432_add_on_min_cost_ratio: float = Field(default=8.0, ge=0, le=1000)
    opportunity_v432_add_on_total_risk_cap_pct: float = Field(default=15.0, ge=0.01, le=100)
    opportunity_v432_add_on_max_initial_quantity_ratio: float = Field(default=0.75, ge=0, le=5)
    opportunity_v432_add_on_min_risk_budget_pct: float = Field(default=0.50, ge=0, le=100)
    opportunity_v432_release_fallback_drawdown_pct: float = Field(default=8.0, ge=0.1, le=100)
    opportunity_v44_full_bet_enabled: bool = True
    opportunity_v44_min_rank_percentile: float = Field(default=0.80, ge=0, le=1)
    opportunity_v44_min_quality_score: float = Field(default=52.0, ge=0, le=100)
    opportunity_v44_min_expected_net_pct: float = Field(default=0.02, ge=-100, le=100)
    opportunity_v44_min_lower_expectancy_pct: float = Field(default=-0.05, ge=-100, le=100)
    opportunity_v44_min_cost_ratio: float = Field(default=1.50, ge=0, le=1000)
    opportunity_v44_min_confirmations: int = Field(default=3, ge=1, le=5)
    opportunity_v44_margin_pct: float = Field(default=90.0, ge=1, le=99)
    opportunity_v44_min_risk_pct: float = Field(default=8.0, ge=0.01, le=100)
    opportunity_v44_max_risk_pct: float = Field(default=15.0, ge=0.01, le=100)
    opportunity_v44_stressed_risk_cap_pct: float = Field(default=15.0, ge=0.01, le=100)
    opportunity_v44_min_leverage: int = Field(default=3, ge=1, le=50)
    opportunity_v44_max_leverage: int = Field(default=10, ge=1, le=50)
    opportunity_v44_cost_stress_multiplier: float = Field(default=1.50, ge=1, le=10)
    opportunity_v44_stop_atr: float = Field(default=0.85, ge=0.05, le=20)
    opportunity_v44_take_profit_r: float = Field(default=1.05, ge=0.1, le=20)
    opportunity_v44_break_even_trigger_r: float = Field(default=0.45, ge=0.05, le=5)
    opportunity_v44_max_hold_bars: int = Field(default=2, ge=1, le=200)
    opportunity_v44_runtime_exit_enabled: bool = True
    opportunity_v462_time_exit_migrated: bool = True
    opportunity_v462_short_min_directed_flow: float = Field(default=0.72, ge=0, le=1)
    opportunity_v462_short_min_regime_fit: float = Field(default=0.85, ge=0, le=1)
    opportunity_v462_short_min_medium_path: float = Field(default=0.45, ge=0, le=1)
    opportunity_v462_short_risk_multiplier: float = Field(default=0.65, ge=0, le=1)
    opportunity_v47_adaptive_enabled: bool = True
    opportunity_v47_seed_version: str = "v4.6.2"
    opportunity_v47_seed_weight: float = Field(default=0.25, ge=0, le=1)
    opportunity_v47_seed_effective_sample_cap: float = Field(default=4.0, ge=0, le=100)
    opportunity_v47_calibration_lookback_hours: float = Field(default=72, ge=24, le=8760)
    opportunity_v47_calibration_max_rows: int = Field(default=4000, ge=100, le=100000)
    opportunity_v47_calibration_cache_seconds: int = Field(default=300, ge=30, le=3600)
    opportunity_v47_min_current_samples: int = Field(default=6, ge=1, le=1000)
    opportunity_v47_full_current_samples: int = Field(default=16, ge=1, le=1000)
    opportunity_v47_threshold_min_current_samples: int = Field(default=12, ge=1, le=1000)
    opportunity_v47_exact_min_samples: int = Field(default=4, ge=1, le=1000)
    opportunity_v47_aligned_multiplier: float = Field(default=1.0, ge=0, le=2)
    opportunity_v47_neutral_multiplier: float = Field(default=0.85, ge=0, le=2)
    opportunity_v47_countertrend_multiplier: float = Field(default=0.65, ge=0, le=2)
    opportunity_v47_min_multiplier: float = Field(default=0.55, ge=0, le=2)
    opportunity_v47_max_multiplier: float = Field(default=1.15, ge=0, le=2)
    opportunity_v47_max_step: float = Field(default=0.10, ge=0, le=0.5)
    opportunity_v47_countertrend_min_directed_flow: float = Field(default=0.72, ge=0, le=1)
    opportunity_v47_countertrend_min_regime_fit: float = Field(default=0.85, ge=0, le=1)
    opportunity_v47_countertrend_min_medium_path: float = Field(default=0.45, ge=0, le=1)
    opportunity_v48_seed_version: str = "v4.7"
    opportunity_v48_min_quality_score: float = Field(default=56.0, ge=0, le=100)
    opportunity_v48_min_expected_net_pct: float = Field(default=0.03, ge=-100, le=100)
    opportunity_v48_min_lower_expectancy_pct: float = Field(default=-0.03, ge=-100, le=100)
    opportunity_v48_min_cost_ratio: float = Field(default=1.70, ge=0, le=1000)
    opportunity_v48_smart_flow_max_points: float = Field(default=2.0, ge=0, le=20)
    opportunity_v48_exhaustion_enabled: bool = True
    opportunity_v48_exhaustion_extension_atr: float = Field(default=0.85, ge=0.01, le=20)
    opportunity_v48_exhaustion_impulse_atr: float = Field(default=1.60, ge=0.01, le=20)
    opportunity_v48_exhaustion_wick_ratio: float = Field(default=2.50, ge=0.01, le=20)
    opportunity_v48_exhaustion_volume_floor: float = Field(default=1.05, ge=0, le=20)
    opportunity_v48_exhaustion_path_floor: float = Field(default=0.18, ge=0, le=1)
    opportunity_v48_exhaustion_caution_score: float = Field(default=0.42, ge=0, le=1)
    opportunity_v48_exhaustion_block_score: float = Field(default=0.62, ge=0, le=1)
    opportunity_v48_exhaustion_caution_multiplier: float = Field(default=0.65, ge=0, le=1)
    opportunity_v48_local_evidence_enabled: bool = True
    opportunity_v48_evidence_hard_min_trades: int = Field(default=20, ge=1, le=100000)
    opportunity_v48_evidence_hard_pf: float = Field(default=0.55, ge=0, le=100)
    opportunity_v48_evidence_caution_multiplier: float = Field(default=0.60, ge=0, le=1)
    opportunity_v48_evidence_caution_quality_delta: float = Field(default=0.04, ge=0, le=1)
    opportunity_v48_reentry_enabled: bool = True
    opportunity_v48_reentry_hard_losses: int = Field(default=2, ge=1, le=20)
    opportunity_v48_reentry_caution_multiplier: float = Field(default=0.70, ge=0, le=1)
    opportunity_v48_reentry_reset_path: float = Field(default=0.25, ge=0, le=1)
    opportunity_v48_reentry_reset_volume: float = Field(default=1.05, ge=0, le=20)
    opportunity_v48_reentry_reset_extension_atr: float = Field(default=0.35, ge=0, le=20)
    opportunity_v44_loss_reduced_after: int = Field(default=2, ge=1, le=20)
    opportunity_v44_loss_reduced_risk_pct: float = Field(default=8.0, ge=0.01, le=100)
    opportunity_v44_max_consecutive_losses: int = Field(default=5, ge=1, le=20)
    opportunity_v44_rotation_min_edge_r: float = Field(default=0.35, ge=0, le=10)
    opportunity_v44_rotation_min_cost_ratio: float = Field(default=1.25, ge=0, le=1000)
    opportunity_v44_release_pause_drawdown_pct: float = Field(default=35.0, ge=0.1, le=100)
    opportunity_v44_global_pf_soft_context: bool = True
    opportunity_v50_min_rank_percentile: float = Field(default=0.85, ge=0, le=1)
    opportunity_v50_min_quality_score: float = Field(default=52.0, ge=0, le=100)
    opportunity_v50_min_expected_net_pct: float = Field(default=0.02, ge=-100, le=100)
    opportunity_v50_min_lower_expectancy_pct: float = Field(default=-0.08, ge=-100, le=100)
    opportunity_v50_min_cost_ratio: float = Field(default=2.50, ge=0, le=1000)
    opportunity_v50_min_confirmations: int = Field(default=2, ge=1, le=5)
    opportunity_v50_margin_pct: float = Field(default=90.0, ge=1, le=100)
    opportunity_v50_min_risk_pct: float = Field(default=12.0, ge=0.01, le=100)
    opportunity_v50_max_risk_pct: float = Field(default=30.0, ge=0.01, le=100)
    opportunity_v50_stressed_risk_cap_pct: float = Field(default=30.0, ge=0.01, le=100)
    opportunity_v50_min_leverage: int = Field(default=3, ge=1, le=50)
    opportunity_v50_max_leverage: int = Field(default=10, ge=1, le=50)
    opportunity_v50_cost_stress_multiplier: float = Field(default=1.50, ge=1, le=10)
    opportunity_v50_stop_atr: float = Field(default=0.90, ge=0.1, le=10)
    opportunity_v50_take_profit_r: float = Field(default=1.05, ge=0.1, le=20)
    opportunity_v50_break_even_trigger_r: float = Field(default=0.45, ge=0.05, le=5)
    opportunity_v50_max_hold_bars: int = Field(default=3, ge=1, le=100)
    opportunity_v50_smart_flow_max_points: float = Field(default=10.0, ge=0, le=20)
    opportunity_v50_initial_multiplier: float = Field(default=1.0, ge=0, le=1)
    opportunity_v50_loss_1_multiplier: float = Field(default=0.80, ge=0, le=1)
    opportunity_v50_loss_2_multiplier: float = Field(default=0.60, ge=0, le=1)
    opportunity_v50_loss_3_multiplier: float = Field(default=1.0, ge=0, le=1)
    opportunity_v50_loss_3_cooldown_minutes: float = Field(default=20.0, ge=1, le=1440)
    opportunity_v51_pullback_min_rank_percentile: float = Field(default=0.80, ge=0, le=1)
    opportunity_v51_prebreakout_min_rank_percentile: float = Field(default=0.82, ge=0, le=1)
    opportunity_v51_breakout_min_rank_percentile: float = Field(default=0.88, ge=0, le=1)
    opportunity_v51_pullback_min_cost_ratio: float = Field(default=2.20, ge=0, le=1000)
    opportunity_v51_prebreakout_min_cost_ratio: float = Field(default=2.30, ge=0, le=1000)
    opportunity_v51_breakout_min_cost_ratio: float = Field(default=2.80, ge=0, le=1000)
    opportunity_v51_breakout_min_confirmations: int = Field(default=3, ge=1, le=5)
    opportunity_v51_panic_recovery_min_rank_percentile: float = Field(default=0.82, ge=0, le=1)
    opportunity_v51_panic_recovery_min_expected_net_pct: float = Field(default=0.04, ge=-100, le=100)
    opportunity_v51_panic_recovery_min_cost_ratio: float = Field(default=2.30, ge=0, le=1000)
    opportunity_v51_panic_recovery_min_confirmations: int = Field(default=3, ge=1, le=5)
    opportunity_v51_recovery_min_volume_acceleration: float = Field(default=1.05, ge=0, le=100)
    opportunity_v51_recovery_min_directed_flow: float = Field(default=0.58, ge=0, le=1)
    opportunity_v51_recovery_min_medium_path: float = Field(default=0.30, ge=0, le=1)
    opportunity_v51_recovery_max_extension_atr: float = Field(default=0.35, ge=0, le=20)
    opportunity_v51_event_group_minutes: int = Field(default=60, ge=1, le=1440)
    opportunity_v511_initial_multiplier: float = Field(default=0.50, ge=0, le=1)
    opportunity_v511_loss_1_multiplier: float = Field(default=0.40, ge=0, le=1)
    opportunity_v511_loss_2_multiplier: float = Field(default=0.25, ge=0, le=1)
    opportunity_v511_same_direction_dedupe_minutes: int = Field(default=120, ge=1, le=1440)
    opportunity_v511_same_direction_window_hours: float = Field(default=6.0, ge=0.25, le=168)
    opportunity_v511_same_direction_max_events: int = Field(default=2, ge=1, le=100)
    opportunity_v511_same_direction_hard_losses: int = Field(default=2, ge=1, le=20)
    opportunity_v511_reentry_caution_multiplier: float = Field(default=0.50, ge=0, le=1)
    opportunity_v52_episode_minutes: int = Field(default=30, ge=1, le=1440)
    opportunity_v52_min_cross_sectional_strength: float = Field(default=0.78, ge=0, le=1)
    opportunity_v52_min_gross_cost_multiple: float = Field(default=3.50, ge=1, le=1000)
    opportunity_v52_momentum_live_enabled: bool = False
    opportunity_v52_evidence_min_episodes: int = Field(default=8, ge=1, le=10000)
    opportunity_v52_evidence_low_pf: float = Field(default=0.75, ge=0, le=1000)
    opportunity_v52_evidence_caution_multiplier: float = Field(default=0.70, ge=0, le=1)
    opportunity_v52_risk_base_pct: float = Field(default=12.0, ge=0.01, le=100)
    opportunity_v52_risk_good_pct: float = Field(default=18.0, ge=0.01, le=100)
    opportunity_v52_risk_strong_pct: float = Field(default=24.0, ge=0.01, le=100)
    opportunity_v52_risk_top_pct: float = Field(default=30.0, ge=0.01, le=100)
    opportunity_v52_hard_stop_reserve_usdt: float = Field(default=0.15, ge=0, le=1000000)
    opportunity_v53_min_rank_percentile: float = Field(default=0.85, ge=0, le=1)
    opportunity_v53_quiet_min_rank_percentile: float = Field(default=0.90, ge=0, le=1)
    opportunity_v53_panic_min_rank_percentile: float = Field(default=0.95, ge=0, le=1)
    opportunity_v53_min_cross_sectional_strength: float = Field(default=0.72, ge=0, le=1)
    opportunity_v53_min_gross_cost_multiple: float = Field(default=3.50, ge=1, le=1000)
    opportunity_v53_min_confirmations: int = Field(default=2, ge=1, le=5)
    opportunity_v53_smart_flow_max_points: float = Field(default=5.0, ge=0, le=20)
    opportunity_v53_adaptive_enabled: bool = True
    opportunity_v53_adaptive_min_episodes: int = Field(default=8, ge=1, le=10000)
    opportunity_v53_adaptive_min_symbols: int = Field(default=3, ge=1, le=10000)
    opportunity_v53_adaptive_min_regimes: int = Field(default=2, ge=1, le=20)
    opportunity_v53_adaptive_rank_step: float = Field(default=0.05, ge=0, le=0.10)
    opportunity_v53_adaptive_expectancy_step_pct: float = Field(default=0.002, ge=0, le=0.10)
    opportunity_v53_adaptive_risk_step: float = Field(default=0.10, ge=0, le=0.10)
    opportunity_v53_release_drawdown_pause_enabled: bool = False
    opportunity_v54_core_rank_percentile: float = Field(default=0.80, ge=0, le=1)
    opportunity_v54_min_cross_sectional_strength: float = Field(default=0.72, ge=0, le=1)
    opportunity_v54_min_gross_cost_multiple: float = Field(default=3.50, ge=1, le=1000)
    opportunity_v54_min_confirmations: int = Field(default=2, ge=1, le=5)
    opportunity_v54_core_max_risk_pct: float = Field(default=15.0, ge=0.01, le=100)
    opportunity_v54_quiet_pullback_max_risk_pct: float = Field(default=10.0, ge=0.01, le=100)
    opportunity_v54_mixed_pullback_max_risk_pct: float = Field(default=12.0, ge=0.01, le=100)
    opportunity_v4_evidence_lookback_hours: float = Field(default=168, ge=1, le=8760)
    opportunity_v4_evidence_max_trades: int = Field(default=5000, ge=100, le=100000)
    opportunity_v4_evidence_cache_seconds: int = Field(default=60, ge=1, le=3600)
    strategy_canary_enabled: bool = True
    strategy_canary_auto_issue: bool = True
    strategy_canary_startup_cap_enabled: bool = True
    strategy_canary_release_id: str = "extreme_v5_roll@v5.2"
    strategy_canary_permit_hours: float = Field(default=24.0, ge=0.25, le=168)
    strategy_canary_level_1_multiplier: float = Field(default=0.50, ge=0, le=1)
    strategy_canary_level_1_max_opportunities: int = Field(default=4, ge=1, le=100)
    strategy_canary_level_2_min_trades: int = Field(default=3, ge=1, le=100)
    strategy_canary_level_2_min_profit_factor: float = Field(default=1.05, ge=0, le=100)
    strategy_canary_level_2_multiplier: float = Field(default=1.0, ge=0, le=1)
    strategy_canary_level_2_max_opportunities: int = Field(default=8, ge=1, le=100)
    strategy_canary_level_3_min_trades: int = Field(default=8, ge=1, le=100)
    strategy_canary_level_3_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    strategy_canary_level_3_multiplier: float = Field(default=1.0, ge=0, le=1)
    strategy_canary_level_3_max_opportunities: int = Field(default=12, ge=1, le=100)
    strategy_canary_max_losses: int = Field(default=3, ge=1, le=20)
    strategy_canary_reissue_enabled: bool = True
    strategy_canary_reissue_observation_minutes: int = Field(default=60, ge=0, le=1440)
    strategy_canary_reissue_min_shadow_trades: int = Field(default=8, ge=1, le=1000)
    strategy_canary_reissue_min_symbols: int = Field(default=3, ge=1, le=1000)
    strategy_canary_reissue_min_profit_factor: float = Field(default=1.15, ge=0, le=100)
    strategy_canary_reissue_multiplier: float = Field(default=1.0, ge=0, le=1)
    strategy_canary_reissue_max_opportunities: int = Field(default=4, ge=1, le=100)
    s0_continuous_permit_enabled: bool = True
    s0_continuous_initial_multiplier: float = Field(default=0.75, ge=0, le=1)
    s0_continuous_loss_1_multiplier: float = Field(default=0.75, ge=0, le=1)
    s0_continuous_loss_2_multiplier: float = Field(default=0.50, ge=0, le=1)
    s0_continuous_loss_3_multiplier: float = Field(default=0.25, ge=0, le=1)
    s0_continuous_daily_tier_1_pct: float = Field(default=10.0, ge=0, le=100)
    s0_continuous_daily_tier_1_multiplier: float = Field(default=0.75, ge=0, le=1)
    s0_continuous_daily_tier_2_pct: float = Field(default=20.0, ge=0, le=100)
    s0_continuous_daily_tier_2_multiplier: float = Field(default=0.50, ge=0, le=1)
    s0_continuous_daily_pause_pct: float = Field(default=30.0, ge=0.1, le=100)
    runtime_protection_supervisor_seconds: int = Field(default=5, ge=2, le=60)
    runtime_protection_stream_price_max_age_seconds: int = Field(default=10, ge=1, le=120)
    s0_continuous_profit_recovery_cost_multiple: float = Field(default=2.0, ge=0, le=100)
    s0_continuous_strong_profit_cost_multiple: float = Field(default=6.0, ge=0, le=100)
    s0_continuous_full_recovery_wins: int = Field(default=2, ge=1, le=20)
    v3_credit_score_weight: float = Field(default=0.15, ge=0, le=2)
    v3_credit_quick_stop_seconds: int = Field(default=300, ge=30, le=3600)
    v3_credit_win_reward: float = Field(default=4.0, ge=0, le=30)
    v3_credit_loss_penalty: float = Field(default=6.0, ge=0, le=40)
    v3_credit_consecutive_loss_penalty: float = Field(default=9.0, ge=0, le=60)
    v3_credit_fee_drag_penalty: float = Field(default=3.0, ge=0, le=30)
    v3_credit_penalty_cooldown_hours: float = Field(default=2.0, ge=0, le=48)
    v3_credit_recovery_interval_hours: float = Field(default=6.0, ge=0.1, le=96)
    v3_credit_recovery_points: float = Field(default=3.0, ge=0, le=30)
    taker_fee_pct_round_trip: float = Field(default=0.08, ge=0, le=5)
    yolo_symbol_trade_score: float = Field(default=60.0, ge=0, le=100)
    yolo_symbol_small_trade_score: float = Field(default=48.0, ge=0, le=100)
    yolo_observe_breakout_min_quality: float = Field(default=58.0, ge=0, le=100)
    yolo_scalp_long_min_profit_factor: float = Field(default=0.55, ge=0, le=20)
    yolo_scalp_long_min_net_pct: float = Field(default=-12.0, ge=-100, le=500)
    yolo_scalp_short_min_recent_trades: int = Field(default=1, ge=0, le=50)
    yolo_scalp_short_min_profit_factor: float = Field(default=0.55, ge=0, le=20)
    yolo_scalp_short_min_net_pct: float = Field(default=-12.0, ge=-100, le=500)
    yolo_scalp_equity_guard_pause_drawdown_pct: float = Field(default=70.0, ge=0.1, le=95)
    extreme_v2_enabled: bool = True
    extreme_v2_profile: str = "standard"
    extreme_firecracker_enabled: bool = True
    extreme_firecracker_min_abs_change_pct: float = Field(default=8.0, ge=0, le=200)
    extreme_firecracker_min_quote_volume_usdt: float = Field(default=30_000_000.0, ge=0)
    extreme_firecracker_volume_score_weight: float = Field(default=12.0, ge=0, le=100)
    extreme_firecracker_move_score_weight: float = Field(default=2.4, ge=0, le=20)
    extreme_firecracker_min_score: float = Field(default=55.0, ge=0, le=200)
    extreme_probe_enabled: bool = True
    extreme_probe_min_score: float = Field(default=78.0, ge=0, le=300)
    extreme_probe_min_firecracker_score: float = Field(default=55.0, ge=0, le=200)
    extreme_probe_risk_multiplier: float = Field(default=0.22, ge=0.01, le=1)
    extreme_probe_max_risk_pct: float = Field(default=6.0, ge=0.1, le=100)
    extreme_probe_min_expected_profit_cost_ratio: float = Field(default=1.05, ge=0, le=100)
    weak_quality_probe_enabled: bool = True
    weak_quality_probe_min_candidate_score: float = Field(default=95.0, ge=0, le=300)
    weak_quality_probe_min_quality_score: float = Field(default=58.0, ge=0, le=100)
    weak_quality_probe_min_cost_ratio: float = Field(default=12.0, ge=0, le=200)
    weak_quality_probe_min_profit_factor: float = Field(default=0.55, ge=0, le=20)
    weak_quality_probe_min_net_pct: float = Field(default=-8.0, ge=-100, le=500)
    weak_quality_probe_min_depth_notional_usdt: float = Field(default=300.0, ge=0)
    weak_quality_probe_max_spread_pct: float = Field(default=0.12, ge=0, le=5)
    weak_quality_probe_base_multiplier: float = Field(default=0.18, ge=0.01, le=1)
    weak_quality_probe_mid_quality_score: float = Field(default=65.0, ge=0, le=100)
    weak_quality_probe_high_quality_score: float = Field(default=72.0, ge=0, le=100)
    weak_quality_probe_mid_multiplier: float = Field(default=0.25, ge=0.01, le=1)
    weak_quality_probe_high_multiplier: float = Field(default=0.35, ge=0.01, le=1)
    weak_quality_probe_low_pf_multiplier: float = Field(default=0.7, ge=0.01, le=1)
    weak_quality_probe_negative_net_multiplier: float = Field(default=0.8, ge=0.01, le=1)
    weak_quality_probe_weak_depth_multiplier: float = Field(default=0.7, ge=0.01, le=1)
    weak_quality_probe_stop_atr: float = Field(default=0.55, ge=0.05, le=10)
    weak_quality_probe_take_profit_atr: float = Field(default=0.75, ge=0.05, le=20)
    weak_quality_probe_max_hold_bars: int = Field(default=3, ge=1, le=200)
    extreme_probe_stop_atr: float = Field(default=0.9, ge=0.05, le=10)
    extreme_probe_take_profit_atr: float = Field(default=1.2, ge=0.05, le=20)
    extreme_probe_max_hold_bars: int = Field(default=4, ge=1, le=200)
    extreme_derivatives_enabled: bool = True
    extreme_oi_check_top_symbols: int = Field(default=12, ge=0, le=100)
    extreme_oi_min_growth_pct: float = Field(default=1.5, ge=-100, le=1000)
    extreme_oi_strong_growth_pct: float = Field(default=4.0, ge=-100, le=1000)
    extreme_funding_abs_crowded_pct: float = Field(default=0.05, ge=0, le=5)
    extreme_derivative_confirm_bonus: float = Field(default=10.0, ge=0, le=100)
    extreme_derivative_divergence_penalty: float = Field(default=12.0, ge=0, le=100)
    extreme_spot_proxy_enabled: bool = True
    extreme_spot_proxy_min_volume_spike: float = Field(default=1.1, ge=0, le=20)
    extreme_spot_proxy_bonus: float = Field(default=6.0, ge=0, le=100)
    extreme_spot_proxy_penalty: float = Field(default=8.0, ge=0, le=100)
    extreme_squeeze_enabled: bool = True
    extreme_squeeze_lookback: int = Field(default=20, ge=10, le=200)
    extreme_squeeze_bonus: float = Field(default=8.0, ge=0, le=100)
    daily_loss_limit_pct: float = Field(default=3.0, ge=0.1, le=60)
    attack_daily_loss_limit_pct: float = Field(default=10.0, ge=0.1, le=60)
    tournament_daily_loss_limit_pct: float = Field(default=25.0, ge=0.1, le=80)
    tournament_sprint_daily_loss_limit_pct: float = Field(default=35.0, ge=0.1, le=90)
    equity_guard_enabled: bool = True
    equity_guard_drawdown_1_pct: float = Field(default=10.0, ge=0, le=100)
    equity_guard_multiplier_1: float = Field(default=0.75, ge=0, le=2)
    equity_guard_drawdown_2_pct: float = Field(default=18.0, ge=0, le=100)
    equity_guard_multiplier_2: float = Field(default=0.45, ge=0, le=2)
    equity_guard_drawdown_3_pct: float = Field(default=25.0, ge=0, le=100)
    equity_guard_multiplier_3: float = Field(default=0.20, ge=0, le=2)
    equity_guard_pause_drawdown_pct: float = Field(default=35.0, ge=0, le=100)
    extreme_equity_guard_pause_drawdown_pct: float = Field(default=40.0, ge=0, le=100)
    min_order_notional_buffer_pct: float = Field(default=3.0, ge=0, le=20)
    effective_position_sizing_enabled: bool = True
    effective_min_order_notional_usdt: float = Field(default=10.0, ge=0, le=10000)
    effective_min_profit_cost_ratio: float = Field(default=3.0, ge=0, le=100)
    effective_min_net_profit_usdt: float = Field(default=0.15, ge=0, le=10000)
    effective_guard_probe_min_multiplier: float = Field(default=0.20, ge=0, le=2)
    effective_guard_standard_min_multiplier: float = Field(default=0.30, ge=0, le=2)
    effective_guard_high_min_multiplier: float = Field(default=0.40, ge=0, le=2)
    effective_guard_top_min_multiplier: float = Field(default=0.60, ge=0, le=2)
    effective_probe_min_risk_pct: float = Field(default=0.50, ge=0, le=100)
    effective_standard_min_risk_pct: float = Field(default=0.80, ge=0, le=100)
    effective_high_min_risk_pct: float = Field(default=1.50, ge=0, le=100)
    effective_top_min_risk_pct: float = Field(default=2.00, ge=0, le=100)
    effective_probe_max_risk_pct: float = Field(default=2.00, ge=0, le=100)
    effective_standard_max_risk_pct: float = Field(default=6.00, ge=0, le=100)
    effective_high_max_risk_pct: float = Field(default=10.00, ge=0, le=100)
    effective_top_max_risk_pct: float = Field(default=14.00, ge=0, le=100)
    max_drawdown_pct: float = Field(default=15.0, ge=1, le=80)
    max_consecutive_losses: int = Field(default=2, ge=1, le=20)
    cooldown_hours: int = Field(default=24, ge=1, le=168)
    max_open_positions: int = Field(default=1, ge=1, le=20)
    tournament_sprint_max_open_positions: int = Field(default=1, ge=1, le=5)
    tournament_sprint_second_position_equity: float = Field(default=100.0, ge=0)
    position_rotation_enabled: bool = False
    position_rotation_shadow_enabled: bool = True
    rotation_validation_min_trades: int = Field(default=50, ge=1, le=10000)
    rotation_validation_min_net_pnl: float = Field(default=0.0, ge=-1000000, le=1000000)
    tournament_rotation_enabled: bool = False
    tournament_sprint_rotation_enabled: bool = False
    extreme_sprint_rotation_enabled: bool = False
    attack_rotation_enabled: bool = False
    balanced_rotation_enabled: bool = False
    conservative_rotation_enabled: bool = False
    tournament_rotation_min_new_score: float = Field(default=95.0, ge=0, le=200)
    tournament_sprint_rotation_min_new_score: float = Field(default=88.0, ge=0, le=200)
    extreme_sprint_rotation_min_new_score: float = Field(default=82.0, ge=0, le=200)
    attack_rotation_min_new_score: float = Field(default=100.0, ge=0, le=200)
    balanced_rotation_min_new_score: float = Field(default=110.0, ge=0, le=200)
    conservative_rotation_min_new_score: float = Field(default=130.0, ge=0, le=200)
    tournament_rotation_min_score_delta: float = Field(default=12.0, ge=0, le=200)
    tournament_sprint_rotation_min_score_delta: float = Field(default=8.0, ge=0, le=200)
    extreme_sprint_rotation_min_score_delta: float = Field(default=8.0, ge=0, le=200)
    attack_rotation_min_score_delta: float = Field(default=18.0, ge=0, le=200)
    balanced_rotation_min_score_delta: float = Field(default=25.0, ge=0, le=200)
    conservative_rotation_min_score_delta: float = Field(default=999.0, ge=0, le=1000)
    rotation_min_cost_ratio: float = Field(default=8.0, ge=0, le=100)
    rotation_min_net_cost_ratio: float = Field(default=2.5, ge=0, le=100)
    rotation_extra_close_cost_pct: float = Field(default=0.08, ge=0, le=5)
    rotation_profit_min_score_delta: float = Field(default=25.0, ge=0, le=200)
    rotation_loss_min_score_delta: float = Field(default=8.0, ge=0, le=200)
    rotation_probe_min_score_delta: float = Field(default=8.0, ge=0, le=200)
    rotation_small_loss_pct: float = Field(default=0.5, ge=0, le=100)
    rotation_keep_winner_profit_pct_extreme: float = Field(default=1.2, ge=0, le=100)
    rotation_unknown_position_score: float = Field(default=75.0, ge=0, le=200)
    rotation_keep_winner_profit_pct: float = Field(default=3.0, ge=0, le=100)
    rotation_max_current_loss_pct: float = Field(default=6.0, ge=0, le=100)
    rotation_cooldown_minutes: int = Field(default=45, ge=0, le=1440)
    max_symbol_margin_pct: float = Field(default=35.0, ge=1, le=100)
    attack_max_symbol_margin_pct: float = Field(default=60.0, ge=1, le=100)
    tournament_max_symbol_margin_pct: float = Field(default=90.0, ge=1, le=100)
    tournament_sprint_max_symbol_margin_pct: float = Field(default=95.0, ge=1, le=100)
    stage1_max_leverage: float = Field(default=2, ge=1, le=10)
    attack_max_leverage: float = Field(default=3, ge=1, le=20)
    tournament_max_leverage: float = Field(default=5, ge=1, le=50)
    tournament_sprint_max_leverage: float = Field(default=5, ge=1, le=50)
    stage2_max_leverage: float = Field(default=1.5, ge=1, le=5)
    min_recent_trades: int = Field(default=2, ge=0, le=50)
    min_profit_factor: float = Field(default=1.2, ge=0, le=10)
    min_expected_profit_cost_ratio: float = Field(default=3.0, ge=0, le=20)
    estimated_slippage_pct: float = Field(default=0.04, ge=0, le=5)
    min_expected_profit_pct: float = Field(default=0.35, ge=0, le=20)
    preemptive_entries_enabled: bool = True
    preemptive_min_score: float = Field(default=72.0, ge=0, le=200)
    preemptive_risk_multiplier: float = Field(default=0.24, ge=0.05, le=1)
    short_preemptive_risk_multiplier: float = Field(default=0.18, ge=0.05, le=1)
    preemptive_max_distance_pct: float = Field(default=0.35, ge=0, le=5)
    tournament_sprint_enabled: bool = True
    tournament_sprint_auto_under_equity: float = Field(default=100.0, ge=0)
    tournament_sprint_standard_min_score: float = Field(default=72.0, ge=0, le=200)
    tournament_sprint_preemptive_min_score: float = Field(default=58.0, ge=0, le=200)
    tournament_sprint_preemptive_max_distance_pct: float = Field(default=0.55, ge=0, le=5)
    tournament_sprint_preemptive_risk_multiplier: float = Field(default=0.35, ge=0.05, le=1)
    tournament_sprint_short_preemptive_risk_multiplier: float = Field(default=0.25, ge=0.05, le=1)
    tournament_sprint_momentum_enabled: bool = True
    tournament_sprint_momentum_min_score: float = Field(default=54.0, ge=0, le=200)
    tournament_sprint_momentum_min_candle_pct: float = Field(default=0.10, ge=0, le=20)
    tournament_sprint_min_expected_profit_cost_ratio: float = Field(default=1.35, ge=0, le=20)
    tournament_sprint_min_expected_profit_pct: float = Field(default=0.22, ge=0, le=20)
    tournament_sprint_standard_stop_atr: float = Field(default=0.9, ge=0.1, le=10)
    tournament_sprint_standard_take_profit_atr: float = Field(default=1.4, ge=0.1, le=20)
    tournament_sprint_standard_max_hold_bars: int = Field(default=6, ge=1, le=100)
    tournament_sprint_preemptive_stop_atr: float = Field(default=0.75, ge=0.1, le=10)
    tournament_sprint_preemptive_take_profit_atr: float = Field(default=1.0, ge=0.1, le=20)
    tournament_sprint_preemptive_max_hold_bars: int = Field(default=4, ge=1, le=100)
    tournament_sprint_momentum_stop_atr: float = Field(default=0.8, ge=0.1, le=10)
    tournament_sprint_momentum_take_profit_atr: float = Field(default=1.2, ge=0.1, le=20)
    tournament_sprint_momentum_max_hold_bars: int = Field(default=5, ge=1, le=100)
    tournament_sprint_short_min_recent_trades: int = Field(default=3, ge=0, le=50)
    tournament_sprint_short_min_profit_factor: float = Field(default=1.05, ge=0, le=10)
    tournament_sprint_short_min_net_pct: float = Field(default=-2.0, ge=-100, le=100)
    tournament_sprint_long_min_profit_factor: float = Field(default=0.85, ge=0, le=10)
    tournament_sprint_long_min_net_pct: float = Field(default=-3.0, ge=-100, le=100)
    tournament_sprint_max_consecutive_losses: int = Field(default=4, ge=1, le=20)
    quality_mode_weights_enabled: bool = True
    sprint_symbol_trade_score: float = Field(default=68.0, ge=0, le=100)
    sprint_symbol_small_trade_score: float = Field(default=55.0, ge=0, le=100)
    sprint_symbol_hot_observe_score: float = Field(default=45.0, ge=0, le=100)
    sprint_atr_ideal_min_pct: float = Field(default=1.2, ge=0, le=100)
    sprint_atr_ideal_max_pct: float = Field(default=7.0, ge=0, le=100)
    sprint_atr_high_pct: float = Field(default=10.0, ge=0, le=100)
    sprint_high_atr_risk_multiplier: float = Field(default=0.6, ge=0, le=1)
    sprint_sample_penalty: float = Field(default=1.0, ge=0, le=20)
    sprint_sample_penalty_exempt_spike: float = Field(default=2.5, ge=0, le=20)
    sprint_sample_low_risk_multiplier: float = Field(default=0.75, ge=0, le=1)
    sprint_hot_observe_risk_multiplier: float = Field(default=0.35, ge=0, le=1)
    sprint_extreme_depth_notional_usdt: float = Field(default=50_000.0, ge=0)
    market_state_filter_enabled: bool = True
    market_state_spike_wick_ratio: float = Field(default=2.2, ge=0, le=20)
    market_state_trap_max_depth_notional_usdt: float = Field(default=800.0, ge=0)
    market_state_min_volume_spike: float = Field(default=1.2, ge=0, le=20)
    min_order_filter_enabled: bool = True
    websocket_trigger_enabled: bool = True
    websocket_trigger_max_events: int = Field(default=240, ge=1, le=500)
    websocket_trigger_scan_limit: int = Field(default=80, ge=1, le=500)
    websocket_trigger_move_pct: float = Field(default=0.35, ge=0, le=20)
    websocket_trigger_quote_volume_usdt: float = Field(default=250_000.0, ge=0)
    observe_breakout_enabled: bool = True
    observe_breakout_min_score: float = Field(default=105.0, ge=0, le=200)
    observe_breakout_min_quality: float = Field(default=78.0, ge=0, le=100)
    observe_breakout_min_cost_ratio: float = Field(default=20.0, ge=0, le=200)
    observe_breakout_min_profit_factor: float = Field(default=1.5, ge=0, le=20)
    observe_breakout_min_net_pct: float = Field(default=4.0, ge=-100, le=500)
    observe_breakout_min_depth_notional_usdt: float = Field(default=500.0, ge=0)
    observe_breakout_max_spread_pct: float = Field(default=0.08, ge=0, le=5)
    observe_breakout_risk_multiplier: float = Field(default=0.22, ge=0.05, le=1)
    observe_low_price_threshold: float = Field(default=0.01, ge=0, le=1000)
    observe_low_price_risk_multiplier: float = Field(default=0.75, ge=0.05, le=1)
    observe_high_atr_pct: float = Field(default=3.0, ge=0, le=100)
    observe_high_atr_risk_multiplier: float = Field(default=0.75, ge=0.05, le=1)
    observe_extreme_atr_pct: float = Field(default=3.0, ge=0, le=100)
    observe_extreme_depth_notional_usdt: float = Field(default=5_000.0, ge=0)
    observe_consecutive_loss_count: int = Field(default=2, ge=0, le=20)
    observe_consecutive_loss_risk_multiplier: float = Field(default=0.5, ge=0.05, le=1)
    directional_cooldown_enabled: bool = True
    legacy_symbol_cooldown_blocks: bool = False
    symbol_cooldown_minutes: int = Field(default=0, ge=0, le=1440)
    stop_loss_cooldown_minutes: int = Field(default=30, ge=0, le=1440)
    allow_short: bool = True
    short_risk_multiplier: float = Field(default=0.5, ge=0.1, le=1)
    short_min_recent_trades: int = Field(default=5, ge=0, le=50)
    short_min_profit_factor: float = Field(default=1.3, ge=0, le=10)
    short_min_net_pct: float = Field(default=1.0, ge=-50, le=100)
    grid_enabled: bool = True
    grid_min_levels: int = Field(default=20, ge=5, le=200)
    grid_max_levels: int = Field(default=80, ge=5, le=300)
    grid_reserve_cash_pct: float = Field(default=25.0, ge=0, le=80)
    grid_stop_on_breakout: bool = True
    dry_run: bool = True
    live_trading_enabled: bool = False
    live_trading_confirmation: str = ""
    binance_base_url: str = "https://fapi.binance.com"
    api_key: str = ""
    api_secret: str = ""


class ExecutePayload(BaseModel):
    symbol: str
    side: str = "BUY"
    quantity: float = Field(gt=0)
    reduce_only: bool = False


class BotControlPayload(BaseModel):
    action: str
    confirmation: str = ""
